packages/docs/docs/dev tools/formatting+linting.md
Oppdaterer dokumentasjon om hvordan vi skal kjøre Biome med File Watcher in Webstorm.
=> doc: update info about linting config for Webstorm

compose.yml, packages/bff/package.json, packages/bff/src/index.ts, packages/bff/src/util/ApplicationInsightsInit.ts, packages/bff/src/util/sessionUtils.ts
Application Insights started nå ved å sende inn ENABLE_APP_INSIGHTS = true env variabel, og HTTPS enables ved env var ENABLE_HTTPS=true.
Fjernet all bruk av isLocal variabel.
=> Added flags for App insights and HTTPS

packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
Bare en bugfix, var en bug som gjorde at Person og Bedrift så likt ut for Sidebar.
=> fix: Storybook now correctly shows company layout

.github/workflows/workflow-check-for-changes.yml, packages/dialogporten-types-generated/package.json, packages/dialogporten-types-generated/src/index.ts, packages/docs/docusaurus.config.ts, packages/frontend-design-poc/package.json, packages/frontend-design-poc/src/api/queries.ts, packages/frontend-design-poc/src/components/FilterBar/filterBar.module.css, packages/frontend-design-poc/src/components/Header/Header.tsx, packages/frontend-design-poc/src/components/InboxItem/inboxItem.module.css, packages/frontend-design-poc/src/components/InboxItem/inboxItemDetail.module.css, packages/frontend-design-poc/src/components/InboxItem/inboxItems.module.css, packages/frontend-design-poc/src/components/InboxItem/inboxItemsHeader.module.css, packages/frontend-design-poc/src/components/MenuBar/MenuBar.tsx, packages/frontend-design-poc/src/components/PageLayout/pageLayout.module.css, packages/frontend-design-poc/src/components/Sidebar/Sidebar.tsx, packages/frontend-design-poc/src/mocks/dialogs.tsx, packages/frontend-design-poc/src/mocks/handlers.ts, packages/frontend-design-poc/src/pages/Inbox/Inbox.tsx, packages/frontend-design-poc/src/pages/Inbox/inbox.module.css, packages/frontend-design-poc/utils/useWindowSize.tsx, packages/storybook/.storybook/preview.tsx, pnpm-lock.yaml, turbo.json
Tar i bruk filterBar-komponent i visning over "mine dialoger" (`inbox`):
- Oppdatert `npm`-pakke for  `types-generated` og eksponere typene
- Har lagt til noe eksempeldata som mockes nå ved `msw` som hentes via `react-query`
- Bruker filterBar-komponenten, foreløpig kun filter er "avsender", med realistisk-ish data.
- Strammen opp visningen visuelt
=> feat: add filter to inbox page

packages/bff/src/userApi.ts, packages/frontend-design-poc/src/api/queries.ts, packages/frontend-design-poc/src/auth/api.ts, packages/frontend-design-poc/src/auth/index.ts, packages/frontend-design-poc/src/auth/url.ts, packages/frontend-design-poc/src/auth/useAuthenticated.ts, packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx, packages/frontend-design-poc/src/main.tsx
Endrer login-flyten til å kalle på endepunkt `isAuthenticated` for å vurdere om login er nødvendig. 
Den sparer på URL og bruker redirectes tilbake tilbake til forlatt klientURL etter å ha autentisert seg mot idporten.
=> feature: improve login flow for app (#436)

compose.yml, packages/bff/src/oidc.ts, packages/frontend-design-poc/src/App.tsx, packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx
Legger til `api/logout` som nuker session, utløper cookie og sender bruke til IDporten logout.
Ved vellykket logout sendes browser til `/loggedout` på klienten.
=> Feature(auth): Log out user

.azure/infrastructure/test.bicepparam, compose.yml
- Azure Cache for Redis only supports 4.0 and 6.0. Setting version to 6.0 for both local development and Azure https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview
=> fix(azure): set supported azure Redis version

.azure/applications/bff/main.bicep, compose.yml, packages/bff/package.json, packages/bff/src/auth/oidc.ts, packages/bff/src/auth/verifyToken.ts, packages/bff/src/server.ts, packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx, pnpm-lock.yaml
Virkende PoC på å hente data via BFF fra Dialogporten i frontend. Bruker fastify-proxy for å reroute trafikk via Bff.
Validerer fortsatt session token og følger ellers normal flyt. Headers omskrives til å tilfredsstille kravene til backend.
Oppskrift:
1. Logg inn med 14886498226
2. trykk på "Test proxy"-knapp over header i klient.
3. Sjekk respons / console.log for dialog tilknyttet bruker
=> poc: example proxying request to dialogporten

packages/docs/docs/business-rules/views.mdx, packages/docs/docs/development/automated+tests.md
cf. https://github.com/digdir/dialogporten-frontend/issues/53
We have landed on a working plan for mapping data to the different views in frontend.
=> doc:  business logic rules (WIP) for dialogs in frontend #469

packages/storybook/.storybook/preview.tsx, packages/storybook/package.json, pnpm-lock.yaml
Legger til `react-query` ti story wrapper for `stories` i `Storybook` slik at komponenter som krever `react-query` ikke krasjer.
=> fix: fixes broken stories in storybook that depends on react-query

.azure/modules/applicationGateway/main.bicep, .azure/modules/containerApp/main.bicep, .azure/modules/vnet/main.bicep
- change default subnet since to 23 because that is what container apps require
- remove protocol from fqdn
- allow non-ssl requests to container apps
=> fix: change default subnet size to 23

packages/bff-types-generated/queries/parties.fragment.graphql, packages/bff-types-generated/queries/parties.graphql, packages/bff-types-generated/schema.ts, packages/bff/src/graphql/api.ts, packages/bff/src/graphql/schema.ts, packages/frontend/src/api/queries.ts, packages/frontend/src/components/PageLayout/PageLayout.tsx
Hente parties for innlogget bruker for å kunne hente dialoger senere (som krever party).
For å kunne generere typer og sdk for `parties`, må bff i tillegg eksportere `stiched schema` (bff + dialogporten) i stedet for rent `bff` schema.
=> feat:  fetch parties from stiched schema (#580)

packages/frontend/src/components/FilterBar/FilterBar.tsx, packages/frontend/src/i18n/resources/nb.json, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Inbox/inbox.module.css
- Flytter Search-knapp fra FilterBar til nivået over
- Fikser bug: Bare oppdatere state dersom initial state har innhold (storybook-eksemplet brakk)
=> refactor: remove search button from filter bar component

packages/frontend/src/components/ActionPanel/ActionPanel.tsx, packages/frontend/src/components/ActionPanel/actionPanel.module.css, packages/frontend/src/components/BottomDrawer/BottomDrawer.tsx, packages/frontend/src/components/BottomDrawer/bottomDrawer.module.css, packages/frontend/src/components/BottomDrawer/index.ts, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/index.ts, packages/storybook/src/stories/ActionPanel/actionPanel.stories.tsx, packages/storybook/src/stories/BottomDrawer/bottomDrawer.stories.tsx
In preparation for re-using it via a portal in the Snackbar component
=> refactor(frontend): move out BottomDrawer as its own component

package.json, packages/bff-types-generated/queries/dialog.fragment.graphql, packages/bff-types-generated/queries/savedSearchesFields.fragment.graphql, packages/bff/src/entities.ts, packages/bff/src/graphql/types/savedSearches.ts, packages/dialogporten-types-generated/package.json, packages/frontend/src/components/Backdrop/backdrop.module.css, packages/frontend/src/components/Backdrop/index.ts, packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx, packages/frontend/src/components/FilterBar/AddFilterButton/addFilterButton.module.css, packages/frontend/src/components/FilterBar/FilterBar.tsx, packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx, packages/frontend/src/components/FilterBar/FilterList/filterList.module.css, packages/frontend/src/components/FilterBar/filterBar.module.css, packages/frontend/src/components/InboxItem/InboxItemDetail.tsx, packages/frontend/src/mocks/dialogs.tsx, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/SavedSearches/EditSearchesItem.tsx, packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx, packages/storybook/src/stories/FilterBar/filterbar.stories.tsx, pnpm-lock.yaml
Feat: Flervalgsstøtte i filter.
Refaktorer FilterBar component til et nivå hvor output kun representeres som `id` og `value`, som i kombinasjon med søkestreng, lagres. All tilleggsinformasjon er ikke nødvendig å lagre, og hentes ut ifra settings / andre props.
Var tvunget til å ta inn endringer i GQL schema fra Dialogporten pga endringer i backend.
=> feature: support multiselect filters 

packages/frontend/src/components/FilterBar/FilterBar.tsx, packages/frontend/src/pages/SavedSearches/SavedSearches.tsx, packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
Fikser feil at filtre inneholder objekter som har verdi `undefined`, som intern i `FilterBar` brukes som placeholder-state for å angi at et filter er valgt, men ikke spesifisert. 
Og erstatter id med `value`:
Samlet fikser dette viewet for lagret søk:
=> fix: remove filters with undefined as value

packages/frontend/src/components/InboxItem/InboxItem.tsx, packages/frontend/src/components/InboxItem/inboxItem.module.css, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PageLayout/SelectedDialogs.tsx, packages/frontend/src/pages/Inbox/Inbox.tsx
n InboxItem, instead the whole item acts as a checkbox.
=> feat(frontend): when in bulk mode it shouldn't be possible to click into

packages/frontend/src/components/Footer/footer.module.css, packages/frontend/src/components/Header/header.module.css, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PageLayout/pageLayout.module.css, packages/frontend/src/globals.css
feat(frontend): make background grey when in bulk selection mode #677
- Update how background is handled, make it stretch the whole screen.
- Make sure that the background is always at least 100vh heigh to cover
the entire screen
- Make background grey when in selection mode
=> feat(frontend): make background grey when in bulk selection mode #542

packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx, packages/frontend/src/components/FilterBar/AddFilterButton/addFilterButton.module.css, packages/frontend/src/components/FilterBar/FilterBar.tsx, packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx, packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css, packages/frontend/src/components/FilterBar/FilterList/FilterListItem.tsx, packages/frontend/src/components/FilterBar/FilterList/filterList.module.css, packages/frontend/src/components/FilterBar/FilterList/filterListItem.module.css, packages/frontend/src/components/FilterBar/dateInfo.ts, packages/frontend/src/components/FilterBar/filterBar.module.css, packages/frontend/src/components/Footer/footer.module.css, packages/frontend/src/i18n/resources/nb.json, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Inbox/inbox.module.css, packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx, packages/frontend/src/pages/SavedSearches/savedSearches.module.css
Ferdigsstiller designet (tror jeg) for basisfunksjonalitet for desktop og større skjermer for FilterBar.
Relative datoer (uker, dag, osv), er skrevet om slik at de alltid er relative i forhold til dagens dato ved senere bruk.
=> feat: finalize-ish design for desktop and larger screens for FilterBar

.editorconfig
EditorConfig is a config standard for defining if you should use tabs or spaces and for which files. They have plugins for all known code editors.
The Dialogporten "backend" uses it and sets their default to 4 spaces. By having a config in our repo as well developers switching between projects get the correct spacing in both projects.
=> chore: editorconfig setup

packages/frontend/src/App.tsx, packages/frontend/src/components/Sidebar/Sidebar.tsx, packages/frontend/src/pages/PageNotFound/PageNotFound.tsx, packages/frontend/src/pages/PageNotFound/index.ts
Sidebar linket fremdeles til /inbox, som ikke lenger er en gyldig route.
Fjernet forstyrrende page not found-page for `no match`, med en redirect til `/` i stedet.
=> fix:  broken linking and improved UX to no match routing

packages/frontend/src/components/ProfileButton/ProfileButton.tsx, packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx, packages/frontend/src/i18n/resources/nb.json, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/storybook/src/stories/ProfileButton/profileButton.stories.tsx
Utvider ProfileButton med loading state som kan brukes for operasjoner som er potensielt tidskrevende.
Eksemplifisert brukt med SavedSearch.
=> feat: make Profilebutton loadable

packages/frontend/src/components/Header/SearchDropdown.tsx, packages/frontend/src/components/InboxItem/inboxItemsHeader.module.css, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/SortOrderDropdown/SortOrderDropdown.tsx, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Inbox/queryParams.ts, packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
- Forandrer interface for gruppering av dialoger for å kunne sortere gruppene kronologisk og kople mer metadata til gruppeinformasjonen. Før var det kun én key.  
- Rydder litt opp i Inbox.tsx
=> feat: cleanup code and make grouping of dialogs more flexible

packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PageLayout/pageLayout.module.css
In the design header and footer takes up the whole width of the screen and are not a part of a grid.
=> feat(frontend): move header and footer out of the grid

compose.yml, oidc-mock/oidc-mock.compose.yml
When starting up Docker Compose they warn that the "version" field is no longer needed.
=> chore: remove "status" field from Docker compose files

packages/frontend/src/api/useDialogById.tsx
Inboxdetaljer ville ikke vises fordi `mainContentReference` (som har mange innslag av `null` i dataene) ikke ble behandlet som `nullable`.
Lukker #861
=> fix: mainContentReference is nullable

packages/frontend/src/components/Backdrop/Modal.tsx, packages/frontend/src/components/Backdrop/backdrop.module.css, packages/frontend/src/components/Backdrop/index.ts, packages/frontend/src/pages/SavedSearches/EditSearchesItem.tsx, packages/frontend/src/pages/SavedSearches/SavedSearches.tsx, packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx, packages/frontend/src/pages/SavedSearches/savedSearches.module.css
Fixes #839
- Ny ModalWithBakcdrop komponent som wrapper Designsystemet sin modal og legger med vår Backdrop. Så vidt jeg kan se så har alle skisser backdrop når det er modaler.
- Mye paddings og margins som fikses
- Noen ekstra ikoner hvor det manglet
_Backdrop, ikoner, padding_
_Backdrop, ikon på slette knapp_
=> fix(frontend): design fixes on saved search

packages/frontend/src/components/InboxItem/inboxItemDetail.module.css, packages/frontend/src/components/PageLayout/pageLayout.module.css, packages/frontend/src/pages/InboxItemPage/InboxItemPage.tsx, packages/frontend/src/pages/InboxItemPage/inboxItemPage.module.css
Ordner marginer og størrelser for hovedramme for inbox-detaljer.
Egen PR for mobil / pad. Egne oppgaver for innhold i visningen, som f.eks. gui-knapper og transmissions.
=> fix: adjustments to layout for desktop for inbox details

packages/bff-types-generated/queries/dialog.fragment.graphql, packages/frontend/src/api/useDialogById.tsx, packages/frontend/src/components/InboxItem/GuiActions.tsx, packages/frontend/src/components/InboxItem/InboxItemDetail.tsx, packages/storybook/src/stories/GuiActions/guiActions.stories.tsx
Prøver å følge spesfikasjonene nedskrevet https://digdir.github.io/dialogporten/#gui-handlinger så tett som mulig.
Det er vanskelig å teste, dvs jeg kan teste mot et mock-endepunkt, men får ikke testet autentiseringsdelen av det.
Fikser #778 (resten 👇 er resteoppgave som krever detaljering):
Kjente mangler (ikke besvart av design):
- Hva skal skje dersom bruker ikke er autentisert til å utføre action (p.t. er knappen deaktivert, men synlig). Bør det forklares hvorfor den er deaktivert?
- Hva skal skje når en dialog slettes som følge av en delete-action (nærliggende at man får redirect til hovedsiden)
=> feat: make gui action buttons work for all http methods

packages/frontend/src/components/Header/SearchDropdown.tsx, packages/frontend/src/components/Header/search.module.css, packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
=> fix: Arrow alignment in search dropdown

packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx, packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css, packages/frontend/src/components/InboxItem/InboxItem.tsx, packages/frontend/src/components/ProfileCheckbox/ProfileCheckbox.tsx, packages/frontend/src/components/ProfileCheckbox/index.ts, packages/frontend/src/components/ProfileCheckbox/profileCheckbox.module.css, packages/storybook/src/stories/ProfileCheckbox/profileCheckbox.stories.tsx
Adds ProfileCheckBox which respects the selected profile scheme (company or person).
Fixes #899 and aligns design with profile.
=> feat: add ProfileCheckbox

packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/Header/SearchBar.tsx, packages/frontend/src/components/Header/header.module.css, packages/frontend/src/components/Header/search.module.css
Justerer layout for søkefelt slik at den ser likt ut på mobil og tablet.
Fikser også et par animasjon- og margin-glitcher. Header er nå forenklet og er pure css mtp layout.
=> fix: fix layout for search bar on mobile and mobile

packages/frontend/package.json, packages/frontend/src/pages/SavedSearches/EditSavedSearchDialog/EditSavedSearchDialog.tsx, packages/frontend/src/pages/SavedSearches/SavedSearchesActions/SavedSearchesActions.tsx, pnpm-lock.yaml
Fjerner heroicons for react-pakke og erstatter de to ikonene som brukes med tilsvarende nav/aksel-ikoner.
Heroicons skal ikke brukes.
Lukker [#948](https://github.com/digdir/dialogporten-frontend/issues/948)
=> fix: remove hero icons

packages/docs/src/pages/index.module.css, packages/frontend/src/components/DropdownMenu/DropdownMobileHeader/dropdownMobileHeader.module.css, packages/frontend/src/components/DropdownMenu/dropdownList.module.css, packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx, packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx, packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css, packages/frontend/src/components/FosToolbar/fosToolbar.module.css, packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/Header/SearchBar.tsx, packages/frontend/src/components/Header/header.module.css, packages/frontend/src/components/Header/search.module.css, packages/frontend/src/components/MenuBar/navigationDropdownMenu.module.css, packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx, packages/frontend/src/components/ProfileButton/ProfileButton.tsx, packages/frontend/src/components/ProfileButton/profileButton.module.css, packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx, packages/frontend/src/components/SortOrderDropdown/SortOrderDropdown.tsx, packages/frontend/src/pages/Inbox/inbox.module.css, packages/storybook/src/stories/ProfileButton/profileButton.stories.tsx
Legger til size `xs` til `ProfileButton` som brukes i dropdown-elementene.
Den har fått egen story i storybook, for ordens skyld.
Det var også tull med headeren og søkefeltet på mobil som var litt kritisk, så det er også en fiks på det.
Fikser #947
=> feat: add xs size for profile button + small fixes in header

packages/bff/package.json, pnpm-lock.yaml
https://npmdiff.dev/%40digdir%2Fdialogporten-schema/1.8.1-3ca495f/1.11.0-161c42b/
=> chore: bump dialogporten-schema to v. 1.11.0-161c42b

packages/bff/src/auth/oidc.ts, packages/bff/src/auth/userApi.ts, packages/bff/src/auth/verifyToken.ts, packages/bff/src/graphql/api.ts, packages/frontend/src/auth/api.ts, packages/frontend/src/auth/useAuthenticated.ts, packages/frontend/src/components/PageLayout/PageLayout.tsx
Forsøk på å løse at man blir unødvendig logget ut.
P.t. refreshes token når tjenestekall gjøres mot BFF og auth_token er utløpt. 
Ettersom flere usynkroniserte kall gjøres i paralllell,. og alle disse vil se behov for å refreshe access_token, vil man få unødvendig refreshing av auth_tokens. For å forhindre dette, er det kun `isAuthenticated`-endepunktet nå som er master og som triggrer en refresh dersom `auth_token` er utløpt. `isAuthenticated` kalles fra klienten hvert 30. sekund for å holde tokenet varmt (for å forhindre utlogging). Forutsetter at tab er aktiv / side er aktiv. 
Mangler (mulige forbedringer som kan avventes):
- Burde ha retries på refreshing av auth_token?
- Kunne refreshe token før det uløper.
=> fix: change refresh auth token flow

packages/bff/package.json, pnpm-lock.yaml
remove  applicationinsights-native-metrics since there are no binaries for > M1, making it impossible to run locally.
=> fix: remove app insights native sdk

packages/bff-types-generated/queries/dialog.fragment.graphql, packages/frontend/src/api/organisations.ts, packages/frontend/src/api/useDialogById.tsx, packages/frontend/src/api/useDialogs.tsx, packages/frontend/src/components/Activity/Activity.tsx, packages/frontend/src/components/Activity/activity.module.css, packages/frontend/src/components/Activity/index.ts, packages/frontend/src/components/Header/SearchDropdown.tsx, packages/frontend/src/components/InboxItem/GuiActions.tsx, packages/frontend/src/components/InboxItem/InboxItem.tsx, packages/frontend/src/components/InboxItem/InboxItemDetail.tsx, packages/frontend/src/components/InboxItem/inboxItemDetail.module.css, packages/frontend/src/components/MainContentReference/MainContentReference.tsx, packages/frontend/src/i18n/resources/en.json, packages/frontend/src/i18n/resources/nb.json, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/InboxItemPage/inboxItemPageSkeleton.module.css, packages/storybook/src/stories/InboxItems/InboxItems.stories.tsx
Show activites for dialogs, rendering description value from service owner rawn for type `informations`, othertwise translating the `type`.
=> feat:  Activity history for dialog detail page

packages/frontend/package.json, packages/storybook/package.json, pnpm-lock.yaml
`react-i18next` begynte å krangle om at den ikke fant typene for `t`-resolver. Så den kom i ny major, så benyttet anledning til å hoppe på den. Testet, og endringene siden v 14 ser harmløse og fornuftige ut. Best av alt er typefeilen fikset.
=> chore: update react-i18next

packages/frontend/src/components/DropdownMenu/dropdownList.module.css, packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx, packages/frontend/src/components/PartyDropdown/PartyList.tsx, packages/frontend/src/components/PartyDropdown/mergeParties.ts, packages/frontend/src/pages/Inbox/Inbox.tsx
- Remove logical grouping of parties when there are only 3 
- Remove bottom padding to partylist 
- Should not remove filter options when selecting an option in a multiple select
- Remove filters with only one option
Closes #883
=> fix: ui improvements to filter bar and menu item

packages/frontend/src/api/useParties.ts, packages/frontend/src/components/Activity/Activity.tsx, packages/frontend/src/components/Avatar/Avatar.tsx, packages/frontend/src/components/GlobalMenuBar/GlobalMenuBar.tsx, packages/frontend/src/components/GlobalMenuBar/NavigationDropdownMenu.tsx, packages/frontend/src/components/GlobalMenuBar/UserInfo.tsx, packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/Header/SearchDropdown.tsx, packages/frontend/src/components/InboxItem/InboxItem.tsx, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PartyDropdown/PartyList.tsx, packages/frontend/src/components/Sidebar/Sidebar.tsx, packages/storybook/src/stories/Avatar/avatar.stories.tsx
Makes Avatar easier to use (API more transparent) by changing visual appearance based on companyName present or not, to instead accept a profile type.
Also fixes bug: `allOrganizationsSelected` not correctly calculated and remove uneccessary "private" label in menu (which was a part of refactor anyways)
=> fix: replace companyName with profile in Avatar

.github/workflows/ci-cd-pull-request-release-please.yml
- Added a new workflow that only triggers on release-PRs made by release-please.
- Will run dry-runs toward staging for both infra and app deployment
- Will send a slack message notifying about a new release in #team-dialogporten-github-frontend
Related to https://github.com/digdir/dialogporten/issues/230
=> ci: add verification on release pr

.github/slack-templates/pipeline-failed.json, .github/workflows/ci-cd-main.yml, .github/workflows/ci-cd-prod.yml, .github/workflows/ci-cd-staging.yml, .github/workflows/workflow-send-ci-cd-status-slack-message.yml
Will send a status message on Slack whenever pipelines are failing. Image is from the backend Slack message. Tweaks for design/improvement on the slack message are welcome..!
Related to https://github.com/digdir/dialogporten/issues/1288
=> ci: alert on slack when pipelines fail

packages/frontend/package.json, packages/frontend/src/api/useDialogs.tsx, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx, packages/frontend/src/components/PageLayout/Search/useSearchDialogs.tsx, packages/frontend/src/pages/Inbox/Inbox.tsx, pnpm-lock.yaml
- onClick on autocomplete items were overridden by on clear in PageLayout (Probably some experimental code that was forgotten?) and re-introduces onClick which was easily missed during a merge conflict after refactoring,
- Since it uses a later version of altinn-components, it includes https://github.com/Altinn/altinn-components/issues/116:
(Layout body should be hidden on mobile when menu is open)
- remove old copy of useSearchDialogs (not in use)
=> fix: autocomplete not working when searching within scope of inbox

packages/frontend/src/app.spec.tsx, packages/frontend/src/mocks/handlers.ts, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx, packages/frontend/tests/stories/dialogDetails.spec.ts, packages/frontend/tests/stories/flatPartySubParty.spec.ts, packages/frontend/tests/stories/inboxItemPage.spec.ts, packages/frontend/tests/stories/loginPartyContext.spec.ts, packages/frontend/tests/stories/messageNavigation.spec.ts, packages/frontend/tests/stories/savedSearch.spec.ts, packages/frontend/tests/stories/sidebar.spec.ts, packages/frontend/tests/stories/smoke.spec.ts
Some tests scenarios are failing because of the application is breaking after we switched to Altinn Components.
I created two tickets and commented out tests that should be later uncommented to maintain the coverage:
https://github.com/digdir/dialogporten-frontend/issues/1562
https://github.com/digdir/dialogporten-frontend/issues/1559
=> chore: re-enable skipped tests after replacing global comps

packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx, packages/frontend/src/mocks/handlers.ts, packages/frontend/tests/stories/flatPartySubParty.spec.ts
It also contains a modified response from `getSearchAutocompleteDialogs` to confirm to the exact response (`SearchAutocompleteDialogFieldsFragment`) we fetch from dialogporten. 
#1562
=> fix: autocomplete includes results for sub parties belonging to selected party

packages/frontend/src/api/useDialogs.tsx, packages/frontend/src/mocks/data/stories/dialog-count/dialogs.ts, packages/frontend/src/mocks/data/stories/dialog-count/parties.ts, packages/frontend/src/mocks/handlers.ts
I also added correct response to mock handler when party list is empty or invalid party id.
#1492
=> fix: flattened subparties were undefined when subparty list was empty

.azure/applications/bff-migration-job/main.bicep, .azure/applications/bff/main.bicep, .azure/applications/frontend/main.bicep, .github/CODEOWNERS, .github/workflows/ci-cd-main.yml, .github/workflows/ci-cd-staging.yml, data/homepage/config/bookmarks.yaml, packages/docs/docusaurus.config.ts, packages/node-logger/package.json
- https://github.com/digdir/dialogporten/issues/1144
=> chore: rename organization name to altinn

packages/frontend/package.json, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/pages/Inbox/queryParams.ts, packages/frontend/tests/accessibility/axe.test.ts, packages/frontend/tests/index.ts, packages/frontend/tests/stories/dateInput2024.spec.ts, packages/frontend/tests/stories/dialogDetails.spec.ts, packages/frontend/tests/stories/filter.spec.ts, packages/frontend/tests/stories/flatPartySubParty.spec.ts, packages/frontend/tests/stories/inboxItemPage.spec.ts, packages/frontend/tests/stories/loginPartyContext.spec.ts, packages/frontend/tests/stories/messageNavigation.spec.ts, packages/frontend/tests/stories/savedSearch.spec.ts, packages/frontend/tests/stories/select-account.spec.ts, packages/frontend/tests/stories/sidebar.spec.ts, packages/frontend/tests/stories/smoke.spec.ts, pnpm-lock.yaml
Selecting a party from account menu in the global menu should, in addition to select party, also navigate the user to the inbox route, if not already there. 
- #1675
=> fix: selecting account from global menu account should also send user to inbox

packages/bff/Dockerfile, packages/bff/package.json, pnpm-lock.yaml, turbo.json
Revert back to use node-logger as workspace dependency and revert a change we did that might have broken for the verify bff deploy step.
=> chore: revert node-logger as workspace dependency and run cmd in Dockerfile for BFF

packages/frontend/tests/accessibility/axe.test.ts
Enabling accessibility tests for all Routes in the app throws many violations. 
Most of them are coming directly from Altinn-Components library and need to be fixed there I believe. 
Suggestion: Enable Playwright accessibility test in altinn-components so it's easier to track where the issues are and fix them.
[#1592](https://github.com/Altinn/dialogporten-frontend/issues/1592)
=> chore: Cover App routes with AxeBuilder in Playwright

packages/embeddable-markdown-html/src/markdown.tsx, packages/embeddable-markdown-html/tests/__snapshots__/markdown.spec.tsx.snap, packages/embeddable-markdown-html/tests/markdown.spec.tsx, packages/frontend/src/api/useDialogById.tsx, packages/frontend/src/components/MainContentReference/MainContentReference.tsx, packages/frontend/src/components/MainContentReference/mainContentReference.spec.tsx, packages/frontend/src/mocks/data/base/helper.ts
`application/vnd.dialogporten.frontchannelembed-url;type=text/markdown` and `application/vnd.dialogporten.frontchannelembed-url;type=text/html` are now supported, alongside _deprecated_ `vnd.dialogporten.frontchannelembed+json;type=markdown ` and `vnd.dialogporten.frontchannelembed+json;type=html`
- #1704
=> fix: adds new media types for front channel embeds

packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx, packages/frontend/src/components/PageLayout/PageLayout.tsx
In case we do not know how many dialogs the selected party has we need to show.
- #1732
=> feat: add inconclusive badge for sidebar when dialog count is unknown

.azure/infrastructure/yt01.bicepparam
We are going to use the centralized key vault for certificates moving forward. The key vault name has been changed in `test` and `yt01` for now. Needs to be done for `staging` and `prod` as well. This is so that we can ensure when certificates are rotated that we use the latest version of the certificate, instead of downloading the certificate into our own key-vault. 
Also not using wildcard certificates anymore. 
- #N/A
=> chore(infra): ensure correct ssl certificate key for yt01 and test

package.json, packages/bff/Dockerfile, packages/docs/Dockerfile, packages/frontend/Dockerfile
Related to https://github.com/nodejs/corepack/issues/612 - causes all version of pnpm (at least 9 >=) to fail because of missing integrity key (validating hash) through corepack 
=> chore(pnpm+corepack): temporary fix for CI / docker locally due to corepack issues

packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Inbox/useGroupedDialogs.spec.tsx, packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
[#1848](https://github.com/Altinn/dialogporten-frontend/issues/1848)
=> fix: Fix dialogs sorting by date

packages/frontend/src/pages/Inbox/Inbox.tsx
Fixes issue with filters not being loaded in Toolbar after reload.
The problem was that filters are empty initially (before dialogs are loaded) and the Toolbar, once it gets the new filters, doesn't apply the changes. To solve this, the length of filters are part of the Toolbar's key, causing the Toolbar to re-render once the dialogs are loaded and the filters are applicable.
- #1920
=> fix: ensure filters are active in Toolbar on reload of state

packages/frontend/src/api/useParties.ts, packages/frontend/src/components/PageLayout/Search/useSearchString.tsx, packages/frontend/src/useGlobalState.ts
**Background**
Since we already use `react-query` for handling global state, I thought it might be handy to abstract some of this boilerplate a cleaner and more reusable hook with a friendly and familiar looking API (using `useState` as inspiration).
This is not for state / cache where response of a request is involved, only for shared state which is explicitly handled.
**useGlobalState**
Instead of manually handling useQuery and queryClient.setQueryData in multiple places, components can now manage global state with a simple [value, setValue] API.
*Before*
```
const { data: allOrganizationsSelected } = useQuery<boolean>({
queryKey: [QUERY_KEYS.ALL_ORGANIZATIONS_SELECTED],
enabled: false,
staleTime: Number.POSITIVE_INFINITY,
initialData: false,
}); …
```
=> chore(refactor): introduce useGlobalState as cleaner shared state utility with a simple API

packages/frontend/src/api/useDialogs.tsx, packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx, packages/frontend/src/components/SavedSearchButton/alreadySaved.spec.ts, packages/frontend/src/components/SavedSearchButton/alreadySaved.ts, packages/frontend/src/pages/SavedSearches/useSavedSearches.tsx
Also removed double toasting confirmation of delete saved search.
- #1934
=> fix: check for if filter already was saved ignored fromView property

packages/frontend/package.json, packages/frontend/src/api/hooks/useDialogById.tsx, packages/frontend/src/components/DialogDetails/DialogDetails.tsx, packages/frontend/src/components/MainContentReference/MainContentReference.tsx, packages/frontend/src/components/MainContentReference/mainContentReference.spec.tsx, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/profile/useProfile.tsx, pnpm-lock.yaml
Reduces amount of requests of getting dialog by id by increasing the stale time (how long the data is considered fresh) significantly and add cache for `fce` for the id on which the fce is related, e.g. id of transmission for contentReference or dialog of id for main content reference. 
Also through discussions with @mbacherycz  , only used virtualized for accounts menu if accounts length > 20, since this is only meant for high performance for slow lists. 
- #1997
=> fix: reduce requests to fce and increase staale time for dialog by id requests

packages/frontend/src/mocks/handlers.ts
I noticed we were missing a mock handler for subscription stream which causes unwanted noise.
=> chore(msw): add mock handler for stream subscription endpoint

packages/bff-types-generated/queries/dialog.fragment.graphql, packages/frontend/src/api/hooks/useDialogById.tsx, packages/frontend/src/components/DialogDetails/DialogDetails.tsx, packages/frontend/src/components/MainContentReference/MainContentReference.tsx, packages/frontend/src/mocks/data/base/helper.ts
Attachments and front channel embeds (both as main content on dialog and content on transmission) can be `unathorized` both  and should not be attempted to or available for the end user.
I seemingly forgot to add content references from dialog history, so this is in place now.
Just to be clear, this is only in order to prevent unwanted noise, not a security measure (this is already taken care of, rightfully so, of Dialogporten).
- #1998
=> fix: skip unauthorized FCE and attachments

renovate.json
Renovate lager PR-er som kun endrer lockfile dersom dependency er innenfor range siden vi ikke har låst versjon per dependency. 
jf. https://docs.renovatebot.com/configuration-options/
default er `auto` som gjør at vi får `update-lockfile ` som bare oppdaterer lockfile, og ikke manifest.
Gå over til pinned nå, ~eller som PR foreslår (her er jeg litt blank - har spurt https://digdir.slack.com/archives/C079D6P85AQ/p1743753569579859?thread_ts=1742975139.237819&cid=C079D6P85AQ ) gå over til "bump" (alltid lage innslag i manifest-fil i PR)~?
Er redd for mer renovate-spam enn nødvendig 😬 
=> chore(renovate): change rangeStategy to pin

packages/bff-types-generated/queries/dialog.fragment.graphql, packages/bff-types-generated/queries/dialogs.graphql, packages/frontend/src/api/hooks/useDialogById.tsx, packages/frontend/src/api/hooks/useDialogs.tsx, packages/frontend/src/api/hooks/useDialogsCount.tsx, packages/frontend/src/api/queries.ts, packages/frontend/src/api/utils/autcomplete.ts, packages/frontend/src/api/utils/dialog.ts, packages/frontend/src/api/utils/viewType.ts, packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx, packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.spec.ts, packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx, packages/frontend/src/components/PageLayout/Search/useSearchDialogs.tsx, packages/frontend/src/constants/queryKeys.ts, packages/frontend/src/i18n/resources/en.json, packages/frontend/src/i18n/resources/nb.json, packages/frontend/src/mocks/data/base/helper.ts, packages/frontend/src/mocks/handlers.ts, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
This PR introduces "Fetch more" button at the bottom of the dialog list to allow users to load additional dialogs beyond the initial 100 (this number is configurable and up for discussion). This enables access to older dialogs within the current folder or view type. This uses [useInfiniteQuery](https://tanstack.com/query/v4/docs/framework/react/reference/useInfiniteQuery) from React Query to implement this pagination behavior cleanly and efficiently.
A few simplifications worth noting:
- Performance on large datasets: Repeatedly fetching more (e.g., for users with 800+ dialogs) may lead to sluggish UI due to rendering many items in the DOM. This is an acceptable trade-off for now, as we expect users to rely more on filters or search for deep navigation. In the future, we can address this …
=> feat: fetch more

packages/frontend/package.json, packages/frontend/src/components/BetaBanner/BetaBanner.tsx, packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx, packages/frontend/src/components/PageLayout/PageLayout.tsx, packages/frontend/src/components/ProfileButton/ProfileButton.tsx, packages/frontend/src/globals.css, packages/frontend/src/i18n/resources/en.json, packages/frontend/src/i18n/resources/nb.json, packages/frontend/src/i18n/resources/nn.json, packages/frontend/src/main.tsx, packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Profile/Actors/Actors.tsx, pnpm-lock.yaml
This PR removes designsystemet as a direct dependency and instead upgrades to the latest version of altinn-components, which now imports and exports components (for now unmodified) from designsystemet.
This aligns with the strategy of gradually bringing in the components we use from designsystemet, exporting them as DS<Component> so they can coexist with existing components for a transitional period. This avoids double imports and allows us to tweak and adapt the DS components to fit the look and behavior of altinn-components. Once they align well, we drop the DS prefix.
- #2044
=> fix: use components from Designsystemet through Altinn components

packages/bff/src/auth/oidc.ts, packages/frontend/src/App.tsx, packages/frontend/src/pages/LogoutPage/FrontChannelLogout.tsx, packages/frontend/src/pages/LogoutPage/LoggedOut.tsx, packages/frontend/src/pages/LogoutPage/index.ts
This PR adds support for frontchannel logout in the app.
- The frontchannel logout URI (`/logout`) has been added as a route in the app.
- When this route is hit (via an iframe from IdPorten), the client extracts `sid` and `iss` from the URL parameters, forwarding the request to BFF's front channel endpoint (`/api/frontchannel-logout`) with these values. It cannot relieve on the cookie (and thus the current session) being available, so i needs to do a lookup in the session store before destroying it, cf. https://docs.digdir.no/docs/idporten/oidc/oidc_func_sso.html#2-h%C3%A5ndtere-utlogging-fra-id-porten-front-channel-logout
- The API endpoint validates `iss`, looks up the session based on `sid`, and deletes the associated session data if found.
- No redirect or user interface is shown – …
=> feat: add route for front channel logout responsibility

.azure/applications/bff-migration-job/main.bicep, .azure/applications/bff-migration-job/prod.bicepparam, .azure/applications/bff-migration-job/staging.bicepparam, .azure/applications/bff-migration-job/test.bicepparam, .azure/applications/bff-migration-job/yt01.bicepparam, .azure/applications/bff/main.bicep, .azure/applications/bff/prod.bicepparam, .azure/applications/bff/staging.bicepparam, .azure/applications/bff/test.bicepparam, .azure/applications/bff/yt01.bicepparam, .azure/applications/frontend/main.bicep, .azure/applications/frontend/prod.bicepparam, .azure/applications/frontend/staging.bicepparam, .azure/applications/frontend/test.bicepparam, .azure/applications/frontend/yt01.bicepparam, .azure/infrastructure/main.bicep, .azure/infrastructure/prod.bicepparam, .azure/infrastructure/staging.bicepparam, .azure/infrastructure/test.bicepparam, .azure/infrastructure/yt01.bicepparam, .azure/modules/containerApp/main.bicep, .azure/modules/containerAppEnv/main.bicep, .azure/modules/containerAppJob/main.bicep, .azure/modules/vnet/main.bicep
Doing the same as we did for Dialogporten. Enabling workload profiles now, setting Consumption as the profile for all applications before we decide on what machines to use here. https://learn.microsoft.com/en-us/azure/container-apps/workload-profiles-overview
TLDR:
- Enables us to use dedicated machines for the container apps. (think Kubernetes nodes)
- Using Consumption aka automatic allocation and scaling for now
**NB:** Would need to recreate the CAEs, so some downtime is expected in each environment. 
- [#2257](https://github.com/Altinn/dialogporten/issues/2257)
=> feat(infra): enable workload profiles for CAE

.azure/infrastructure/main.bicep, .azure/modules/applicationGateway/main.bicep
The container app environment subnet is exclusive to the container app environment. Will think that we can use the app gateway subnet to create the private link instead. 
- #N/A
=> fix(infra): avoid using containerappenv subnet for private link in app gateway

packages/frontend/src/pages/Inbox/Inbox.tsx, packages/frontend/src/pages/Inbox/filters.ts, packages/frontend/src/pages/Inbox/useGroupedDialogs.spec.tsx, packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
The count for dialog matching the filter, should only count dialogs that are relevant for filters already applied (i.e. dialogs is has fetched already). 
Further more, if results (filter applied or search string provided) are listed in inbox, they should be grouped by folder, sorted by the logical order they appear in. 
- #2217
=> fix: show counts only for contented that is fetched when filter is applied

packages/fastify-graphiql/src/index.ts
the graphiql cdn links all of a sudden disappeared. We probably should not trust these cdn mirrors. I tried creating a new version of this plugin (but ran into issues and give up to not waste time).
Quick fix: change urls that work
=> fix(deps): change (downgrade) missing cdn links that disappeared

.github/slack-templates/pipeline-failed.json, .github/workflows/ci-cd-main.yml, .github/workflows/ci-cd-prod.yml, .github/workflows/ci-cd-staging.yml, .github/workflows/ci-cd-yt01.yml, .github/workflows/workflow-send-ci-cd-status-slack-message.yml, .github/workflows/workflow-upload-source-maps.yml, packages/docs/docs/deployment/applications.md, packages/frontend/.dockerignore, packages/frontend/vite.config.ts
Supersedes https://github.com/Altinn/dialogporten-frontend/pull/2299
This PR adds functionality to upload source maps to Azure Blob Storage for better error tracking and debugging in Application Insights across all environments.
- **Added** `.github/workflows/workflow-upload-source-maps.yml` - New reusable workflow for uploading source maps to Azure Blob Storage
- **Added** source maps upload job to all CI/CD workflows:
- `ci-cd-main.yml` (test environment)
- `ci-cd-staging.yml` 
- `ci-cd-yt01.yml`
- `ci-cd-prod.yml`
- **Updated** Vite configuration in `packages/frontend/vite.config.ts` to generate source maps with `sourcemap: 'hidden'`
- **Added** `.dockerignore` rule in `packages/frontend/.dockerignore` to exclude source maps from Docker builds
- **Updated** Slack notification templates …
=> chore(apps): upload source maps to app insights on deploy

packages/frontend/src/api/hooks/useDialogById.tsx, packages/frontend/src/api/utils/activities.tsx, packages/frontend/src/api/utils/transmissions.ts
Transmissions will now be shown as read if a corresponding "activity" with type "Transmission Opened" type exists for the given transmission id.
- #1954
=> feat: Transmission will now be shown as read based on activities

.azure/infrastructure/main.bicep, .azure/infrastructure/prod.bicepparam, .azure/infrastructure/staging.bicepparam, .azure/infrastructure/test.bicepparam, .azure/infrastructure/yt01.bicepparam, .azure/modules/applicationGateway/main.bicep
Added a maintenance page backend pool that points to the maintenance site created in https://github.com/Altinn/dialogporten-frontend/issues/2544
Ways of switching to maintenance mode:
- Do a switch in the portal and re-deploy the gateway
- Enable the maintenance mode in the bicepparam and redeploy
- #2544
=> feat(infra): add maintenance page to application gateway

packages/frontend/src/api/queries.ts
Using the correct way of setting headers when tracking gql queries. 
- #2628
=> fix(frontend): use correct way of setting headers when tracking

packages/frontend/src/analytics.ts
Still seeing issues related to page view durations.. Ensuring we always set this to 0 would likely solve the issue once and for all. 
- #N/A
=> fix(frontend): avoid errors from AI calculating page durations

packages/bff/src/auth/oidc.ts, packages/bff/src/auth/verifyToken.ts, packages/frontend/src/api/hooks/useDialogById.tsx, packages/frontend/src/api/hooks/useDialogs.tsx, packages/frontend/src/api/hooks/useDialogsCount.tsx, packages/frontend/src/api/hooks/useParties.ts, packages/frontend/src/auth/api.ts, packages/frontend/src/auth/useAuthenticatedInfiniteQuery.tsx, packages/frontend/src/auth/useAuthenticatedQuery.tsx, packages/frontend/src/components/Login/AuthContext.tsx, packages/frontend/src/components/PageLayout/Search/useAutocomplete.tsx, packages/frontend/src/pages/Inbox/useOrganizations.ts, packages/frontend/src/pages/Profile/useNotificationSettingsForParty.tsx, packages/frontend/src/pages/Profile/usePartiesWithNotificationSettings.tsx, packages/frontend/src/pages/Profile/useProfile.tsx, packages/frontend/src/pages/SavedSearches/useSavedSearches.tsx
- Add `useAuthenticatedQuery` and `useAuthenticatedInfiniteQuery` hooks
that only run when `isAuthenticated` is true
- Replace direct useQuery/useInfiniteQuery calls with the new hooks
to avoid running API calls before tokens are refreshed
- BFF: redirect to /api/login on OIDC state mismatch
- BFF: introduce explicit `access_token_invalid` status
https://github.com/Altinn/dialogporten-frontend/issues/2763
=> fix: add authenticated query hooks and improve token handling
