Altinn/dialogporten-frontend

- .github/actions/yarn-install/action.yaml
- .github/workflows/frontend-unit-tests.yml
- .gitignore
- package.json
- src/App.test.tsx
- src/App.tsx
- src/setupTests.ts
- tsconfig.json
- yarn.lock
Added github workflows for linting, building and testing.
- https://github.com/Altinn/altinn-studio/issues/11062
> Added github workflows and actions

- package.json
- src/App.module.css
- src/App.test.tsx
- src/App.tsx
- src/components/ErrorMessage/ErrorMessage.tsx
- src/components/ErrorMessage/errorMessage.module.css
- src/components/ErrorMessage/index.ts
- src/public/index.html
- src/routes/PageLayout/PageLayout.module.css
- src/routes/PageLayout/PageLayout.tsx
- src/routes/RouterErrorMessage.tsx
- src/routes/TestPage/TestPage.tsx
- src/routes/routes.tsx
- yarn.lock
Added React Router to the project and a couple of test routes.
- https://github.com/Altinn/altinn-studio/issues/11056
> Added React Router to project

- CODEOWNERS
The CODEOWNERS file will ensure that the correct people are automatically added as reviewers on new PR's.
> 💪 CODEOWNERS setup

- pnpm-lock.yaml
- pnpm-workspace.yaml
- storybook/.gitignore
- storybook/.storybook/main.ts
- storybook/.storybook/preview.ts
- storybook/README.md
- storybook/index.html
- storybook/package.json
- storybook/pnpm-lock.yaml
- storybook/src/App.tsx
- storybook/src/main.tsx
- storybook/src/stories/Button.stories.ts
- storybook/src/stories/Button.tsx
- storybook/src/stories/Configure.mdx
- storybook/src/stories/button.css
- storybook/src/vite-env.d.ts
- storybook/tsconfig.json
- storybook/tsconfig.node.json
- storybook/vite.config.ts
> #157 feat: Added Storybook

- Readme.md
📝 Add `fzf` to setup instructions in Readme
> 📝 Add `fzf` to setup instructions in Readme

- packages/bff/package.json
Remove unused scripts and not needed fields
> 🔧 Remove unused fields in `bff`'s `package.json`

- packages/frontend-design-poc/src/components/Footer/Footer.tsx
- packages/frontend-design-poc/src/components/Footer/footer.module.css
- packages/frontend-design-poc/src/components/Footer/index.ts
- packages/frontend-design-poc/src/components/index.ts
- packages/frontend-design-poc/src/i18n/resources/nb.json
- packages/frontend-design-poc/src/pages/PageLayout/PageLayout.tsx
- packages/storybook/src/stories/Footer/footer.stories.ts
> feat: Add Footer component to PageLayout

- packages/storybook/.storybook/main.ts
- packages/storybook/.storybook/preview.tsx
- packages/storybook/package.json
- pnpm-lock.yaml
Legger til UU-sjekk på story i Storybook. Dette skjer automatisk med addon, og reglene er hentet og satt via `axe-core`.
> feat: Update Storybook config and add accessibility rules

- .github/pull_request_template.md
> Vår egen PR-mal for Github #232

- packages/frontend-design-poc/vite.config.ts
Kun en forenkling av `defineConfig` for å slippe redudans.
jf. pr
> refactor: Update vite.config.ts for better readability

- .husky/pre-commit
- package.json
- packages/docs/docs/dev tools/husky.md
- pnpm-lock.yaml
Jeg har forenklet det slik at husky er nå på root-nivå med en pre-commit hook som kjører format og linting på de ulike prosjektfilene som er _staged_.
Skal squashe unødvendige commits når jeg merger. 
Står beskrevet i doc.
> Add husky precomit

- .github/workflows/cd-docs.yml
> ci: deploy `docs` and `storybook` to Github Pages

- packages/dialogporten-types-generated/.gitignore
- packages/dialogporten-types-generated/Readme.md
- packages/dialogporten-types-generated/dialogporten-v1.json
- packages/dialogporten-types-generated/package.json
- packages/dialogporten-types-generated/src/index.ts
- pnpm-lock.yaml
[🚀 Generate TypeScript types and code based on OpenAPI Spec](https://github.com/digdir/dialogporten-frontend/pull/269/commits/870603765a0ea20bdafeefa66d38ecbbb3cbf258)
> 🚀 Generate TypeScript types and code based on OpenAPI Spec

- packages/bff-frontend-poc/tsconfig.json
- packages/frontend-design-poc/package.json
- packages/frontend-design-poc/src/app.module.css
- packages/frontend-design-poc/src/components/ActionPanel/ActionPanel.tsx
- packages/frontend-design-poc/src/components/BackButton/BackButton.tsx
- packages/frontend-design-poc/src/components/Header/Header.tsx
- packages/frontend-design-poc/src/components/InboxItem/InboxItem.tsx
- packages/storybook/.storybook/preview.tsx
- packages/storybook/package.json
- packages/storybook/tsconfig.json
- pnpm-lock.yaml
> Migrated to new designsystem packages (#299)

- packages/frontend-design-poc/src/app.module.css
- packages/frontend-design-poc/src/main.tsx
Byttet svak import fra css til main. Flere styles som ikke ble lastet inn riktig.
> fix: css styles from designsystem-css not loaded

- .azure/applications/bff-frontend-poc/main.bicep
- .azure/applications/bff-frontend-poc/test.bicepparam
- .azure/applications/frontend-design-poc/main.bicep
- .azure/applications/frontend-design-poc/test.bicepparam
- .github/workflows/ci-cd-main.yml
- .github/workflows/workflow-deploy-apps.yml
- .github/workflows/workflow-docker-build-and-push.yml
- Sørg for at image er bygd før deployment
- Legg til relevante tjenester for utrulling
> ci: enable relevant apps for deployment

- .azure/applications/bff-migration-job/main.bicep
- .azure/infrastructure/main.bicep
- .azure/modules/applicationInsights/create.bicep
- packages/bff/src/index.ts
- packages/bff/src/util/ApplicationInsightsInit.ts
- bruk korrekt naming for migration-job
- Sørg for at application insights er aktivert for container app environment og 
- Enable app insights for bff
> fix(azure): add application insights and create container app env

- packages/frontend-design-poc/src/components/Avatar/Avatar.tsx
- packages/frontend-design-poc/src/components/Avatar/avatar.module.css
- packages/frontend-design-poc/src/components/Avatar/index.ts
- packages/frontend-design-poc/src/components/Footer/footer.module.css
- packages/frontend-design-poc/src/components/Header/AltinnLogo.tsx
- packages/frontend-design-poc/src/components/Header/Header.tsx
- packages/frontend-design-poc/src/components/Header/header.module.css
- packages/frontend-design-poc/src/components/MenuBar/MenuBar.tsx
- packages/frontend-design-poc/src/components/MenuBar/MenuBarItem.tsx
- packages/frontend-design-poc/src/components/MenuBar/index.tsx
- packages/frontend-design-poc/src/components/MenuBar/menubar.module.css
- packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx
- packages/frontend-design-poc/src/components/PageLayout/pageLayout.module.css
- packages/frontend-design-poc/src/components/Sidebar/Sidebar.tsx
- packages/frontend-design-poc/src/components/Sidebar/sidebar.module.css
- packages/frontend-design-poc/src/components/Sidebar/sidebarItem.module.css
- packages/frontend-design-poc/src/i18n/resources/nb.json
- packages/frontend-design-poc/utils/useWindowSize.tsx
Startet på jobben med å gjøre siden mer responsiv.
Oppdaterte også designet ettersom det var store endringer her siden siste implementasjon.
Denne jobben er ikke ferdig, men merger inn for å ikke ha for store PRs og heller jobbe iterativt.
> Added responsiveness. Updated according to design changes. (#285)

- .github/workflows/workflow-deploy-apps.yml
> ci: remove unused secret in workflow

- .github/workflows/ci-cd-main.yml
- package.json
- release-please-config.json
Versjon var ikke satt ettersom vi ikke har version i package.json.
> ci: ensure version is set

- .azure/applications/bff-migration-job/main.bicep
- .azure/modules/containerAppJob/main.bicep
- .github/workflows/ci-cd-main.yml
- Fikser en valideringsissue for migrationjob. 
- Fikser config-fil til release-please
> ci: fix release please config

- compose.yml
- packages/bff-graphql-poc/Dockerfile
- packages/bff-graphql-poc/package.json
- packages/bff-graphql-poc/src/debug-screen.tsx
- packages/bff-graphql-poc/src/env.ts
- packages/bff-graphql-poc/src/graphql.ts
- packages/bff-graphql-poc/src/index.ts
- packages/bff-graphql-poc/src/schema.ts
- packages/bff-graphql-poc/tsconfig.json
- packages/fastify-graphiql/Readme.md
- packages/fastify-graphiql/package.json
- packages/fastify-graphiql/src/index.ts
- pnpm-lock.yaml
Created a proof-of-concept for a GraphQL server running on top of Fastify
- Using Fastify as web server
- Using `graphql-http` and `graphql-ws` as transports for GraphQL
- Using `zod` to parse enviroment varibales
- `Dockerfile` and `compose.yml` setup
> Beginning of GraphQL POC

- biome.json
- packages/bff/tsconfig.json
> Changed biome settings

- .azure/applications/bff/main.bicep
- .azure/modules/containerApp/main.bicep
- packages/bff/src/ApplicationInsightsInit.ts
- packages/bff/src/config.ts
- packages/bff/src/data-source.ts
- packages/bff/src/index.ts
- packages/bff/src/routes/HealthProbes.ts
- packages/bff/src/run-migration.ts
- Remove the dependency for index.ts in health check, app insights and migration files to avoid booting the app server when running migrations. Rather separating version into `config.ts` and passing `app` as a parameter to the health probes
- Add environment variables for the `bff` app. 
- Add connection string for postgresql for `bff`
> fix(bff): avoid running app on migration

- .azure/applications/bff/main.bicep
- .azure/applications/bff/test.bicepparam
- .azure/modules/containerApp/main.bicep
> fix(azure): separate custom domain into param

- packages/docs/docs/id-porten/id-porten.mdx
Describing our apps authentication flow
> docs: Beginning of ID Porten docs

- Readme.md
Kort avsnitt om dotenv-variabler i Readme.
> docs(env) Update environment setup in Readme.md

- packages/docs/docs/development/automated+tests.md
- packages/frontend-design-poc/src/components/Header/header.module.css
- packages/frontend-design-poc/src/components/MenuBar/MenuBar.tsx
- packages/frontend-design-poc/src/components/MenuBar/menubar.module.css
- packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx
- packages/frontend-design-poc/src/components/Sidebar/sidebarItem.module.css
- packages/storybook/package.json
- packages/storybook/src/stories/Header/Header.stories.tsx
- pnpm-lock.yaml
Forslag til teststrategi med noen konkrete eksempler.
> doc(testing) add intial draft for testing strategy #315

- packages/bff/Dockerfile
The container app won't start now. Refactor to use the start script for booting the service
> fix(bff): use correct command in dockerfile

- packages/bff-graphql-poc/Dockerfile
- packages/bff-graphql-poc/package.json
- packages/bff-graphql-poc/src/env.ts
- pnpm-lock.yaml
```
$ docker image ls -a
REPOSITORY                                  TAG       IMAGE ID       CREATED          SIZE
bff-graphql-poc                             latest    ca0dad9402c3   5 minutes ago    276MB
```
> fix(bff-graphql-poc): smaller Docker image size

- .azure/applications/bff/main.bicep
- compose.yml
> fix: uncomment bff-migration from compose

- packages/bff-graphql-poc/Dockerfile
> feat(bff-graphql-poc): Better caching in Docker build

- packages/frontend-design-poc/src/App.tsx
- packages/frontend-design-poc/src/app.css
- packages/frontend-design-poc/src/components/Footer/footer.module.css
- packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx
- packages/frontend-design-poc/src/components/Sidebar/sidebar.module.css
- packages/frontend-design-poc/src/globalColors.css
- packages/storybook/.storybook/preview.tsx
- packages/storybook/src/stories/Header/Header.stories.tsx
- packages/storybook/src/stories/Sidebar/Sidebar.stories.tsx
> CSS colors now using CSS files instead of javascript

- packages/frontend-design-poc/src/components/PageLayout/PageLayout.tsx
- packages/frontend-design-poc/src/featureFlags/FeatureFlags.ts
- packages/frontend-design-poc/src/featureFlags/FeatureFlagsProvider.tsx
- packages/frontend-design-poc/src/featureFlags/index.ts
- packages/frontend-design-poc/src/featureFlags/useFeatureFlag.ts
- packages/frontend-design-poc/src/main.tsx
- packages/frontend-design-poc/utils/test-utils.tsx
> Added FeatureToggling

- compose.yml
Setup of Redis and Redisinsight (debug UI)
> feat: Setup of Redis & Redisinsight in Docker Compose

- .azure/applications/bff/main.bicep
- .azure/infrastructure/main.bicep
- .azure/infrastructure/test.bicepparam
- .azure/modules/redis/main.bicep
Fixes #414
- Adds Redis in Azure with some default parameters and stores the connection string in key vault
- Adds the connection string as a secret/environment variable for `bff`
> feat(azure): add Redis

- packages/bff-graphql-poc/Dockerfile
This reverts commit f03f06a9951b0bd2359fe15e306c10534b4c53ef.
> Revert "feat(bff-graphql-poc): Better caching in Docker build"

- Readme.md
> doc: Update command in Readme to be `make dev`

- .azure/infrastructure/main.bicep
- .azure/modules/redis/main.bicep
- In order to inject a vnet into Redis we need to be on Premium mode. Private link is the recommended approach. Let's disable for now to get the application gateway working..
> fix(azure): remove vnet from Redis

- CODEOWNERS
> ci: Add Are to CODEOWNERS

- .azure/applications/frontend-design-poc/main.bicep
- .azure/modules/containerApp/main.bicep
- Container is carshlooping because of missing health check endpoints. Changing the probes to point to root
> fix(azure): add health checks for frontend poc

- .azure/infrastructure/main.bicep
- .azure/modules/postgreSql/create.bicep
- Use private link instead of a vnet subnet as it seems to be the preferred way of connecting to redis and postgresql
> fix(azure): revert vnet in favor of private link

- .azure/infrastructure/main.bicep
- .azure/modules/containerAppEnv/main.bicep
- Something weird is happening in the upsert of container app env with subnet. Removing until we land application gateway + vnet here.
> chore: remove subnet for container app env

- biome.json
- packages/dialogporten-types-generated/codegen.ts
- packages/dialogporten-types-generated/package.json
- packages/frontend-design-poc/src/mocks/dialogs.tsx
- pnpm-lock.yaml
> feat: new package with type from dialogporten, and added GraphQL types

- .azure/applications/bff-migration-job/main.bicep
- .azure/applications/bff/main.bicep
- .azure/modules/containerAppJob/main.bicep
- compose.yml
- Set secrets for idPorten values
- Removed unused secrets
> chore(azure): set the appropriate environment variables and secrets

- .azure/applications/bff-migration-job/main.bicep
- .azure/applications/bff/main.bicep
- Azure does not like camelcasing (sometimes)
> chore(azure): rename secret names to alphanumericish

- .azure/modules/postgreSql/create.bicep
- packages/bff/src/data-source.ts
> fix(azure): ensure we use ssl for postgresql connections

- .azure/applications/bff/main.bicep
- .azure/modules/containerApp/main.bicep
> chore: use correct identity string for managed identity

- .azure/applications/bff/main.bicep
- .azure/applications/frontend-design-poc/main.bicep
- .azure/modules/containerApp/main.bicep
- Changed port for both frontend and bff to 80
- Use the correct path for liveness and readiness for bff
> fix: use correct path for probes

- packages/bff/Dockerfile
- Container app is failing because the exposed port in the Dockerfile is 3000 :assumption:
> chore: use correct port for bff

- .github/workflows/ci-cd-main.yml
- .github/workflows/workflow-check-for-changes.yml
- .github/workflows/workflow-deploy-apps.yml
- Only run migrations if relevant files are changed
- Run the deployment of apps regardless of if migration was run
> ci: only run migrations if revelant files changed

- compose.yml
- packages/bff/package.json
> fix: quickfix for broken docker command

- packages/bff/src/server.ts
> fix: actually use the port variable

- packages/bff/src/auth/oidc.ts
`session.destroy()` ble ikke kjørt
> fix: fixes logout not working

- .azure/modules/redis/main.bicep
- Copied the same format as for BE. Adjusting to correct connection string format
> fix(azure): use correct connection string format for redis

- compose.yml
- packages/bff/src/index.ts
- Ensure we `await` the start functions to catch all errors
- Add health check for Redis in `compose.yml`
-
> fix: await start functions to ensure errors are logged

- Makefile
- dev
Let's you choose what stuff in `compose.yml` that you want to start
> feat: better start script

- .github/workflows/ci-cd-main.yml
- Allows us to manually dispatch the main workflow, forcing all jobs to execute
- Added some dependencies and missing if's.
> ci: allow dispatch of main ci-cd

- .azure/modules/vnet/main.bicep
- Container apps requires atleast a /23 subnet size. It is now using the default subnet, so changed the subnet to accomodate that. But forgot to adjust the gateway subnet which now overlaps the default subnet.
> chore: ensure subnets do not overlap

- .azure/modules/applicationGateway/main.bicep
Application Gateway does not support systemassigned identities yet.. So adding an identity explicitly
related to https://github.com/digdir/dialogporten-frontend/issues/441
> chore: use user assigned identity for app gateway

- packages/bff-types-generated/.gitignore
- packages/bff-types-generated/codegen.ts
- packages/bff-types-generated/package.json
- packages/bff-types-generated/queries/hello.graphql
- packages/bff-types-generated/schema.ts
- packages/bff-types-generated/src/index.ts
- packages/bff-types-generated/tsconfig.json
- packages/bff/package.json
- packages/bff/src/app.ts
- packages/bff/src/index.ts
- packages/frontend/package.json
- pnpm-lock.yaml
- turbo.json
> feat: codegen for frontend based on GraphQL types in the BFF (#541)

- packages/bff-types-generated/codegen.ts
- packages/bff-types-generated/package.json
- packages/bff-types-generated/src/index.ts
- packages/bff/package.json
- packages/bff/src/auth/userApi.ts
- packages/dialogporten-types-generated/codegen.ts
- packages/dialogporten-types-generated/package.json
- packages/dialogporten-types-generated/src/index.ts
- packages/fastify-graphiql/src/index.ts
- packages/frontend/package.json
- packages/frontend/src/api/queries.ts
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- pnpm-lock.yaml
Lagt til `graphl-request` med genererte typer.
Har lagt til manglende deps i `bff-types-generated` og riktig eksport av de generete typene og funksjonene.
> feat: add graphql-request for fetching data with example (#543)

- .azure/applications/bff-migration-job/main.bicep
- packages/bff/package.json
- Re-add the "typeorm" script to make migrations work again
- Change the command for the container app job to ensure we run the correct command
> fix(bff): bff migrations

- compose.yml
> Remove Redis cache locally

- package.json
- pnpm-lock.yaml
> ci: add back mprocs thats used by `./dev`

- compose.yml
This should mean that there are fewer times we need to stop and restart it manually. The current setup is by no means exhaustive.
> ci: adding more Watch rules to the compose.yml file

- packages/bff-types-generated/codegen.ts
- packages/bff/Dockerfile
- packages/bff/package.json
- packages/bff/src/auth/userApi.ts
- packages/bff/src/config.ts
- packages/bff/src/graphql/api.ts
- packages/bff/tests/example.spec.ts
- packages/dialogporten-types-generated/codegen.ts
- packages/dialogporten-types-generated/gql-to-ts.js
- packages/dialogporten-types-generated/package.json
- packages/dialogporten-types-generated/src/index.ts
- packages/dialogporten-types-generated/tests/example.spec.ts
- packages/dialogporten-types-generated/tests/validate-schema.spec.ts
- packages/docs/tsconfig.json
- packages/frontend/src/api/queries.ts
- packages/frontend/src/mocks/dialogs.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/storybook/tsconfig.json
- packages/storybook/tsconfig.node.json
- pnpm-lock.yaml
> Stiching GraphQL from Dialogporten backend into the BFF

- packages/bff/src/migrations/1705494567002-init.ts
- packages/bff/src/migrations/1705494611335-init.ts
> cleanup: remove unused migrations

- packages/frontend/Dockerfile
- packages/frontend/nginx.conf
> feat(frontend): updated nginx config 

- .azure/modules/applicationGateway/main.bicep
After a bit back and forth with Azure support, it seems like the name of the private link IP configuration has too many characters in it.. 🙃 No feedback in portal or the ARM deployment..
> chore: fix issue with naming for private link in app gateway

- packages/bff-types-generated/queries/dialog.fragment.graphql
- packages/bff-types-generated/queries/dialogs.graphql
- packages/dialogporten-types-generated/package.json
- packages/frontend/src/api/queries.ts
- packages/frontend/src/api/useDialogs.ts
- packages/frontend/src/api/useParties.ts
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/main.tsx
- packages/frontend/src/mocks/dialogs.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- pnpm-lock.yaml
Hente dialoger fra GQL med brukeren parties.
> feat: get dialogs fra gql

- .azure/modules/applicationGateway/main.bicep
> chore: ensure private link configuration finds frontend ip configuration

- .azure/applications/bff/main.bicep
> chore: add env variable for typeorm sync

- packages/frontend/src/components/ActionPanel/ActionPanel.tsx
- packages/frontend/src/components/ActionPanel/actionPanel.module.css
Updating the style of bulkmode to better match the updated design in Figma. Still more work to be done on #542, but splitting it up into multiple PR's.
> feat(frontend): bulkmode updated design #542

- packages/frontend/src/components/ActionPanel/ActionPanel.tsx
> fix(frontend): quickfix types for actionpanel

- packages/frontend/src/components/PageLayout/PageLayout.tsx
Add the query param `?query=true` to show Leva
> feat(frontend): conditionally show leva

- packages/frontend/src/components/ActionPanel/actionPanel.module.css
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/inbox.module.css
> style(frontend): entry animation for action panel

- .azure/applications/bff/main.bicep
- packages/bff/src/config.ts
> fix(bff): add the correct graphql endpoint

- packages/frontend/src/components/ActionPanel/actionPanel.module.css
> feat(frontend): mobile view for action panel / bulk select

- .azure/applications/bff/test.bicepparam
- .azure/infrastructure/test.bicepparam
- .azure/modules/dnsZones/create.bicep
- Change hostname to the new hostname af.at.altinn.cloud
- Still waiting for certificates so using the old one for now.
More information about status on domain/certs: https://github.com/Altinn/altinn-platform/issues/787
> chore(azure): change hostname in Test

- packages/frontend/src/components/MenuBar/DropDownMenu.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
Remove the functionallity from Leva, and add it to the menu
> feat(frontend): working logout button

- .graphql
- package.json
- packages/bff-types-generated/codegen.ts
- packages/bff-types-generated/graphql.config.yml
- packages/bff-types-generated/queries/hello.graphql
- packages/bff/package.json
- packages/dialogporten-types-generated/package.json
- packages/docs/docs/development/graphql+IDE-support.md
- pnpm-lock.yaml
Setup + minimalistic doc for å sette opp autocomplete, validering og litt snacks for IDE-ene vi bruker.
> doc: recommend plugins for IDE with graphql support

- packages/frontend/package.json
- packages/storybook/package.json
- pnpm-lock.yaml
Oppdatert fort pakkene frontend og storybook med versjon satt til @next 
Ser ikke til å ha merkbare forskjeller, eller noe som bryter ved testing.
> chore(deps): update @digdir/designsystemet-* dependencies for storybook and frontend

- .github/workflows/workflow-deploy-apps.yml
- .github/workflows/workflow-deploy-infrastructure.yml
> chore(azure): fix deployment of infra and apps

- .github/workflows/dispatch-deploy-apps.yml
- .github/workflows/dispatch-deploy-infrastructure.yml
Add dispatch actions like described in the deployment section of the docs. By specifying environment, tag and wether or not to run the migration or not, infrastructure and apps can be deployed manually by these dispatches
> ci: add dispatch to deploy infra and apps

- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/PageLayout/SelectedDialogs.tsx
- packages/frontend/src/components/PageLayout/index.ts
- packages/frontend/src/components/index.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/utils/test-utils.tsx
- packages/storybook/.storybook/preview.tsx
Sidemenyet forsvinner når i bulk modus
> feat(fronted): hide sidebar when in bulk select mode #542

- .github/workflows/ci-cd-staging.yml
Related to https://github.com/digdir/dialogporten-frontend/issues/619
> ci: add staging workflow

- .github/pr-title-checker-config.json
- .github/workflows/ci-cd-pull-request-title.yml
Fails the build if the pull request title doesn't follow the guidelines. Regex: "^(feat|fix|docs|test|ci|chore)!?(\\(.*\\))?!?:.*"
> ci: add pull request title checker

- .azure/infrastructure/main.bicep
- .azure/modules/privateDnsZoneGroup/main.bicep
- .azure/modules/redis/main.bicep
- .azure/modules/vnet/main.bicep
> chore(azure): add private link to redis

- packages/bff-types-generated/queries/dialogs.graphql
- packages/dialogporten-types-generated/package.json
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- pnpm-lock.yaml
> feat: implement backend search functionality for search bar (#627)

- packages/dialogporten-types-generated/package.json
- pnpm-lock.yaml
> feat: update dialogporten schema

- packages/frontend/src/components/ActionPanel/actionPanel.module.css
- packages/frontend/src/components/BottomDrawer/bottomDrawer.module.css
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/Snackbar/Snackbar.tsx
- packages/frontend/src/components/Snackbar/snackbar.module.css
- packages/frontend/src/globals.css
- packages/storybook/src/stories/ActionPanel/actionPanel.stories.tsx
- packages/storybook/src/stories/BottomDrawer/bottomDrawer.stories.tsx
- packages/storybook/src/stories/Snackbar/snackbar.stories.tsx
- Snackbar and ActionPanel can work together if both are open
- Snackbar is center aligned
- Snackbar with new color
> feat(frontend): snackbar in updated design

- biome.json
Added some config folders to the biome ignore list
> feat: updated biome ignore list

- packages/docs/src/pages/index.module.css
- packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/addFilterButton.module.css
- packages/frontend/src/components/FilterBar/FilterBar.tsx
- packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx
- packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css
- packages/frontend/src/components/FilterBar/FilterList/filterList.module.css
- packages/frontend/src/components/FilterBar/dateInfo.spec.ts
- packages/frontend/src/components/FilterBar/dateInfo.ts
- packages/frontend/src/components/FilterBar/filterBar.module.css
- packages/frontend/src/components/MenuBar/menubar.module.css
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
- packages/storybook/src/stories/FilterBar/filterbar.stories.tsx
- Utvider FilterBar til å støtte underlementer av options, dvs flere nivåer av navigasjon, og støtte for å håndtere datoer og og kalenderperioder som skal kunne sorteres på.
- Bruker felt fra data og filtrere data basert på filtrene
> feat: support multi level and date for Filterbar

- packages/frontend/src/components/Avatar/avatar.module.css
- packages/frontend/src/components/Header/header.module.css
- packages/frontend/src/components/MenuBar/menubar.module.css
- packages/frontend/src/globals.css
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/SavedSearches/savedSearches.module.css
> chore: Added more CSS color variables according to Figma design (#623)

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- pnpm-lock.yaml
Brukes ikke lenger, så vi trenger ikke å ha den i koden for å komplisere PageLayout.
> chore: remove Leva, no longer needed

- .azure/modules/vnet/main.bicep
- To ensure we do not mix subnets, we rather use the resourceId() function
- Add NSG for the default subnet
> chore(azure): ensure proper output for subnet ids

- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/Header/Header.tsx
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/Inbox/Inbox.tsx
> fix: Improved search result listing

- packages/frontend/src/App.tsx
- packages/frontend/src/pages/Home/Home.tsx
- packages/frontend/src/pages/Home/index.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
Show inbox as main entry point and remove unnecessary Home component.
> feat: inbox as entry

- packages/frontend/package.json
- packages/frontend/src/components/FilterBar/dateInfo.spec.ts
- packages/frontend/src/components/FilterBar/dateInfo.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/filters.spec.ts
- packages/frontend/src/pages/Inbox/filters.ts
Tests provided. Minor refactoring.
> fix: filter that share id should be exclusive

- packages/bff/Readme.md
- packages/bff/src/azure/ApplicationInsightsInit.ts
- packages/bff/src/db.ts
- packages/bff/src/entities.ts
- packages/bff/src/migrations/1718697208348-initial.ts
- packages/bff/src/run-migration.ts
> feat(bff): update DB migration code #553

- packages/frontend/src/components/DropdownMenu/dropdownList.module.css
- packages/frontend/src/components/DropdownMenu/dropdownList.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/addFilterButton.module.css
- packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css
- packages/frontend/src/components/FilterBar/filterBar.module.css
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/PageLayout/pageLayout.module.css
- packages/frontend/src/components/Sidebar/sidebar.module.css
- packages/frontend/src/components/SortOrderDropdown/SortOrderDropdown.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/inbox.module.css
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
> feat: enable sorting for view

- packages/frontend/src/components/Avatar/Avatar.tsx
- packages/frontend/src/components/Avatar/avatar.module.css
- packages/frontend/src/components/Header/Header.tsx
- packages/frontend/src/components/Header/SearchBar.tsx
- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/Header/SearchDropdownItem.tsx
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/components/InboxItem/inboxItem.module.css
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
> feat: Added search dropdown, typeahed, saved searches listing ++

- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
> chore: Refactor time since logic

- packages/frontend/src/components/Backdrop/backdrop.module.css
- packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/addFilterButton.module.css
- packages/frontend/src/components/FilterBar/filterBar.module.css
- packages/frontend/src/components/Header/SearchBar.tsx
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/SortOrderDropdown/SortOrderDropdown.tsx
- packages/frontend/src/components/SortOrderDropdown/sortOrderDropdown.module.css
> fix: Backdrop fix

- packages/bff-types-generated/queries/dialog.fragment.graphql
- packages/dialogporten-types-generated/package.json
- pnpm-lock.yaml
> fix: update query for Dialogporten gql schema v 1.8.1

- packages/frontend/src/components/Footer/Footer.tsx
- packages/frontend/src/components/Header/Header.tsx
- packages/frontend/src/components/Sidebar/Sidebar.tsx
- packages/frontend/tests/example.spec.ts
> fix: improve smoke-test so multiple headers, footers and sidebars are allowed

- packages/frontend/src/pages/Inbox/Inbox.tsx
> feat(frontend): show snackbar message on when clicking the actionpanel

- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/Header/SearchDropdownSkeleton.tsx
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/InboxSkeleton.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesSkeleton.tsx
Inbox skeleton:
SavedSearches skeleton:
Searchbar skeleton:
> feat: Added skeleton view to Inbox, Search and SavedSearches

- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuProfile.tsx
- packages/frontend/src/components/MenuBar/navigationMenu.module.css
> feat: Updated parties menu according to Figma design

- packages/bff-types-generated/queries/dialog.fragment.graphql
- packages/dialogporten-types-generated/package.json
- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- pnpm-lock.yaml
Endringer i datamodell, korrigert mapping - ikke helt 100 % compat med tidligere, men var uansett ikke ferdig.
> fix: updates for 1.8.1-dbe296a

- packages/frontend/src/components/InboxItem/inboxItem.module.css
- packages/frontend/src/pages/Inbox/InboxSkeleton.tsx
- packages/frontend/src/pages/InboxItemPage/InboxItemPage.tsx
- packages/frontend/src/pages/InboxItemPage/InboxItemPageSkeleton.tsx
- packages/frontend/src/pages/InboxItemPage/inboxItemPageSkeleton.module.css
> feat: Added skeleton loading for InboxItemPage

- .azure/applications/bff-migration-job/main.bicep
- .azure/applications/bff/main.bicep
> fix(bff): remove migration synchronization 

- .azure/applications/bff-migration-job/staging.bicepparam
- .azure/applications/bff/staging.bicepparam
- .azure/applications/frontend/staging.bicepparam
- .azure/infrastructure/staging.bicepparam
> chore(azure): add bicepparams for staging

- .azure/infrastructure/main.bicep
- .azure/modules/privateDnsZoneGroup/main.bicep
- .azure/modules/redis/main.bicep
- .azure/modules/vnet/main.bicep
Based off of this PR https://github.com/digdir/dialogporten-frontend/pull/694
> chore(azure): add redis private link

- .azure/modules/redis/main.bicep
- .github/workflows/workflow-check-for-changes.yml
The deployment of the migration app was not triggered when altering bicep files. Added relevant files in the "check-for-changes"-workflow
> ci: run migrations if bicep changed

- packages/docs/docs/development/formatting+linting.md
> docs: update Webstorm doc for Biome on auto-save

- packages/frontend/package.json
- packages/frontend/src/components/Footer/footer.module.css
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/inboxItem.module.css
- packages/frontend/src/components/InboxItem/inboxItems.module.css
- packages/frontend/src/components/InboxItem/inboxItemsHeader.module.css
- packages/frontend/src/components/MenuBar/NavigationDropdownMenu.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownMenuItem.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuInbox.tsx
- packages/frontend/src/components/MenuBar/NavigationMenuBar.tsx
- packages/frontend/src/components/MenuBar/navigationMenu.module.css
- packages/frontend/src/components/Sidebar/Sidebar.tsx
- packages/frontend/src/components/Sidebar/SidebarItem.tsx
- packages/frontend/src/components/Sidebar/sidebarItem.module.css
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/Inbox/inbox.module.css
- packages/storybook/package.json
- pnpm-lock.yaml
And update arrangement and iconscons and misc improvements.
> feat: indicate viewtype selected in sidebar

- packages/frontend/src/api/queries.ts
> fix(frontend): remove some unused stuff from api/queries

- .azure/applications/bff/main.bicep
- .azure/applications/bff/test.bicepparam
- .azure/applications/frontend/main.bicep
- .azure/applications/frontend/test.bicepparam
- .azure/modules/containerApp/main.bicep
Adjusting min and max replicas for `bff` and `frontend` for high(er) availability.
> chore(azure): adjust replicas for bff and frontend

- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx
- packages/frontend/src/components/FilterBar/dateInfo.spec.ts
- packages/frontend/src/components/FilterBar/dateInfo.ts
- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/i18n/useDateFnsLocale.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/filters.spec.ts
- packages/frontend/src/pages/Inbox/filters.ts
- packages/frontend/src/pages/SavedSearches/EditSearchesItem.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
> feat(frontend): date-fns wrapper to use selected lang

- packages/bff-types-generated/queries/parties.fragment.graphql
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/api/useParties.ts
- packages/frontend/src/components/ActionPanel/actionPanel.module.css
- packages/frontend/src/components/DropdownMenu/dropdownListItem.module.css
- packages/frontend/src/components/FosToolbar/fosToolbar.module.css
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/GuiActions.tsx
- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
- packages/frontend/src/components/PartyDropdown/index.ts
- packages/frontend/src/components/PartyDropdown/partyDropdown.module.css
- packages/frontend/src/components/Snackbar/snackbar.module.css
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/Inbox/Inbox.tsx
Et par todo som gjenstår, nevnt i kode, og helt sikkert en del justeringer i CSS. Men dette er kladd / utgangspunkt som fungerer til videre iterasjon.
> feat: draft of Party dropdown

- biome.jsonc
- packages/frontend/public/mockServiceWorker.js
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/api/useParties.ts
- packages/frontend/src/components/ActionPanel/ActionPanel.tsx
- packages/frontend/src/components/Backdrop/Backdrop.tsx
- packages/frontend/src/components/BottomDrawer/BottomDrawer.tsx
- packages/frontend/src/components/FilterBar/FilterBar.tsx
- packages/frontend/src/components/FilterBar/dateInfo.spec.ts
- packages/frontend/src/components/Footer/footer.module.css
- packages/frontend/src/components/Header/SearchDropdownItem.tsx
- packages/frontend/src/components/InboxItem/GuiActions.tsx
- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownMenu.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownMenuItem.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuInbox.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuProfile.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/PageLayout/SelectedDialogs.tsx
- packages/frontend/src/components/Snackbar/Snackbar.tsx
- packages/frontend/src/components/Snackbar/useSnackbar.spec.ts
- packages/frontend/src/components/Snackbar/useSnackbar.ts
- packages/frontend/src/featureFlags/FeatureFlagsProvider.tsx
- packages/frontend/src/featureFlags/useFeatureFlag.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/profile/useProfile.tsx
- packages/frontend/utils/test-utils.tsx
- packages/frontend/vite.config.ts
> chore: Fixing all lint errors on frontend package

- .azure/applications/bff-migration-job/production.bicepparam
- .azure/applications/bff/production.bicepparam
- .azure/applications/frontend/production.bicepparam
- .azure/infrastructure/production.bicepparam
The max replicas and other scaling configuration needs to be changed for production to ensure scale. However, keeping it as is to save some costs during summer.
> chore(azure): add bicep params for production

- .gitignore
- package.json
- packages/bff-types-generated/package.json
- packages/dialogporten-types-generated/package.json
- pnpm-lock.yaml
- turbo.json
Turborepo v2 supports new watch mode and interactive tasks (looks very similare to mprocs)
Read more at https://turbo.build/blog/turbo-2-0
> chore: update turborepo to v2

- packages/frontend/src/components/BottomDrawer/bottomDrawer.module.css
> fix(frontend): clickthrough on BottomDrawer

- packages/embeddable-markdown-html/Readme.md
- packages/embeddable-markdown-html/package.json
- packages/embeddable-markdown-html/src/html.tsx
- packages/embeddable-markdown-html/src/index.ts
- packages/embeddable-markdown-html/src/markdown.tsx
- packages/embeddable-markdown-html/tests/__snapshots__/html.spec.tsx.snap
- packages/embeddable-markdown-html/tests/__snapshots__/markdown.spec.tsx.snap
- packages/embeddable-markdown-html/tests/html.spec.tsx
- packages/embeddable-markdown-html/tests/markdown.spec.tsx
- packages/embeddable-markdown-html/tests/setup.ts
- packages/embeddable-markdown-html/tsconfig.json
- packages/embeddable-markdown-html/vite.config.js
- packages/embeddable-markdown-html/vitest.config.ts
- pnpm-lock.yaml
> feat: embeddable content for Markdown & Html

- package.json
- pnpm-lock.yaml
> chore: Update Biome

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
- Remove `lint-staged` since Biome have a built inn `--staged` flag
- Update husky script to call Biome directly (ref comment above)
- Add a prepare script so that Husky actually runs locally, needed first time after cloning the repo
After running `pnpm prepare` you should be able to check your setup as following:
```bash
$ git config core.hooksPath
.husky/_
```
> chore: fix husky setup

- .github/workflows/workflow-build-and-test.yml
> chore: enable biome ci

- .github/actions/install/action.yaml
- pnpm/action-setup automatically checks verison thats in package.json
- Also; make actions/setup-node use the .node-version file so that its centralized
> ci: update version of pnpm/action-setup to v4

- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/Header/SearchBar.tsx
- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/Header/header.module.css
- packages/frontend/src/components/Header/search.module.css
- Laget ny SearchBar komponent fra scratch
- Endret useDialogs hook til å returnere tomt søk ved søkelengde < 2 chars
- Lagt til knapp for å resette søk (dersom det er skrevet inn søkestreng)
- Lagt til knapp for å lukke søk (dersom det IKKE er skrevet inn søkestreng)
- Pixel perfect implementasjon av Figma-design
> feat: New search component, design fixes

- packages/frontend/src/components/BackButton/backButton.module.css
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/inboxItemDetail.module.css
- packages/frontend/src/components/InboxItem/inboxItems.module.css
- packages/frontend/src/components/InboxItem/inboxItemsHeader.module.css
- packages/frontend/src/components/PageLayout/pageLayout.module.css
- packages/frontend/src/components/Sidebar/SidebarItem.tsx
- packages/frontend/src/components/Sidebar/sidebar.module.css
- packages/frontend/src/components/Sidebar/sidebarItem.module.css
> fix: Pixel perfect implementation of Figma design

- packages/frontend/src/components/Header/SearchBar.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
> fix: Search will now work if user is on i.e. /saved-searches route

- packages/embeddable-markdown-html/package.json
- packages/embeddable-markdown-html/src/html.tsx
- packages/embeddable-markdown-html/tests/__snapshots__/html.spec.tsx.snap
- packages/embeddable-markdown-html/tests/html.spec.tsx
- pnpm-lock.yaml
> feat(embedabble-markdown-html): sanitize html for security

- packages/dialogporten-types-generated/package.json
- pnpm-lock.yaml
> chore: @digdir/dialogporten-schema v1.8.1-cd03956

- packages/frontend/src/components/Avatar/avatar.module.css
- packages/frontend/src/components/MenuBar/MenuItem.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownMenu.tsx
- packages/frontend/src/components/MenuBar/NavigationMenuBar.tsx
- packages/frontend/src/components/MenuBar/UserInfo.tsx
- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/MenuBar/navigationDropdownMenu.module.css
- packages/frontend/src/components/MenuBar/navigationMenuBar.module.css
- packages/frontend/src/components/MenuBar/userInfo.module.css
> fix: Mobile design implementation of inbox and menu bar

- .azure/applications/bff/staging.bicepparam
> chore: change staging hostname

- packages/embeddable-markdown-html/src/html.tsx
- packages/embeddable-markdown-html/src/markdown.tsx
- packages/frontend/package.json
- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- packages/storybook/package.json
- packages/storybook/src/stories/embeddable-markdown-html/html.stories.tsx
- packages/storybook/src/stories/embeddable-markdown-html/markdown.stories.tsx
- pnpm-lock.yaml
- Storybook stories for embedable content
- Parse field and use <Markdown> in frontend
> feat(frontend): embeddable content

- packages/frontend/src/api/useDialogById.tsx
> fix(frontend): fix if there is no mainContentRefrence

- packages/bff/src/azure/ApplicationInsightsInit.ts
ref https://x.com/mattpocockuk/status/1813670916368527738
> feat(bff): use node:timers

- packages/frontend/src/components/Footer/footer.module.css
> fix(frontend): center footer

- packages/frontend/src/components/InboxItem/inboxItem.module.css
> fix(frontend): fix outline and underline on hover

- .azure/applications/frontend/production.bicepparam
- .azure/applications/frontend/staging.bicepparam
Adding a temporary number of min and max replicas for the `frontend` app. Will be adjusted together with keda autoscaling eventually.
> chore(frontend): set max and minreplicas for all envs

- packages/frontend/src/components/ProfileButton/profileButton.module.css
> fix(frontend): 2px button border-radius

- packages/frontend/src/components/MenuBar/menuItem.module.css
> fix(frontend): square icon

- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/PageLayout/pageLayout.module.css
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/SavedSearches/EditSearchesItem.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
- packages/frontend/src/pages/SavedSearches/savedSearches.module.css
Laget confirm delete dialogboks for sletting av lagrede søk.
Denne må oppdateres når design foreligger.
Div andre bugfixes.
> feat: New design, added delete popup wireframe

- packages/bff-types-generated/queries/dialog.fragment.graphql
- packages/dialogporten-types-generated/package.json
- pnpm-lock.yaml
> chore: @digdir/dialogporten-schema 1.8.1-a635fcb

- packages/bff/package.json
- pnpm-lock.yaml
> chore: @digdir/dialogporten-schema 1.8.1-af262b1

- .release-please-manifest.json
> chore(release-please): rename generated-types package

- packages/embeddable-markdown-html/Readme.md
> docs: fix typo

- packages/docs/package.json
- pnpm-lock.yaml
> chore(dep): update Docusauros to latest version

- .github/workflows/workflow-deploy-docs.yml
> fix: pages doc not working

- .github/workflows/workflow-deploy-docs.yml
- compose.yml
- packages/docs/docusaurus.config.ts
Det må undersøkes hvor BASEURL ikke blir lest inn eller overstyrt, men inntil videre går det fint å snu om på default-verdiene for at det skal virke.
> fix: testing again, changing default baseurl

- packages/frontend/src/components/DropdownMenu/dropdownList.tsx
- packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx
- packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css
- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/MenuBar/navigationDropdownMenu.module.css
- packages/frontend/src/components/MenuBar/navigationMenuBar.module.css
- packages/frontend/src/components/MenuBar/userInfo.module.css
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/Inbox/filters.ts
> feat: Filter toolbar design 

- packages/bff/package.json
- pnpm-lock.yaml
Update schema introduction transmissions.
> chore(dep): update @digdir/dialogporten-schema to 1.8.1-3ca495f

- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/inboxItem.module.css
> fix: Dropdown overflow issue

- packages/docs/docs/deployment/github-actions.md
> docs: rename from action to workflow

- package.json
- pnpm-lock.yaml
work-around, needed for older version of Storybook.
> chore: remove jackspeak dependencary resolution

- packages/frontend/package.json
- packages/frontend/src/components/ActionPanel/ActionPanel.tsx
- packages/frontend/src/components/BackButton/BackButton.tsx
- packages/frontend/src/components/Backdrop/Modal.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx
- packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx
- packages/frontend/src/components/FosToolbar/FosToolbar.tsx
- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/components/InboxItem/InboxItemsHeader.tsx
- packages/frontend/src/components/InboxItem/inboxItem.module.css
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuProfile.tsx
- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
- packages/frontend/src/components/ProfileButton/ProfileButton.tsx
- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
- packages/frontend/src/components/SortOrderDropdown/SortOrderDropdown.tsx
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem.tsx
- packages/storybook/package.json
- packages/storybook/src/stories/ProfileButton/profileButton.stories.tsx
- pnpm-lock.yaml
En del endringer, blant annet med size og color.
Har sammenliknet ganske tett gammel (i dev-miljøet) og ny versjon nå, og det ser ut som migreringen har gått fint.
Eneste er at lukking av modal (i designsystemet) ikke ser ut til å fungere, men etter @TheKnarf uansett jobber med vår egen modal-komponent der, er det ikke farlig.
> fix: update to latest version of digdir-designsystemet-* 

- .azure/applications/bff-migration-job/main.bicep
- .azure/applications/bff/main.bicep
- .azure/applications/frontend/main.bicep
- .azure/infrastructure/main.bicep
- .azure/modules/appConfiguration/create.bicep
- .azure/modules/appConfiguration/upsertKeyValue.bicep
- .azure/modules/applicationGateway/main.bicep
- .azure/modules/applicationInsights/create.bicep
- .azure/modules/containerApp/main.bicep
- .azure/modules/containerAppEnv/main.bicep
- .azure/modules/containerAppJob/main.bicep
- .azure/modules/keyvault/copySecrets.bicep
- .azure/modules/keyvault/create.bicep
- .azure/modules/keyvault/upsertSecret.bicep
- .azure/modules/postgreSql/create.bicep
- .azure/modules/privateDnsZone/main.bicep
- .azure/modules/redis/main.bicep
- .azure/modules/vnet/main.bicep
To separate resources between Arbeidsflate and Dialogporten we add a Product-tag. Environment tag to separate environments.
> feat(azure): add tags on azure infra and applications

- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuProfile.tsx
> fix: Parties not showing private parties now fixed

- packages/frontend/src/components/MenuBar/MenuItem.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuInbox.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuProfile.tsx
- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/MenuBar/navigationDropdownMenu.module.css
- packages/frontend/src/components/MenuBar/navigationMenuBar.module.css
- packages/frontend/src/components/MenuBar/userInfo.module.css
> fix: Dropdown link hitbox. Closing menu when redirecting.

- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
Fixes https://github.com/digdir/dialogporten-frontend/issues/885
> fix: Switching account immediate changes profile 

- packages/frontend/src/components/Header/SearchDropdownSkeleton.tsx
> fix: skeleton not rendering issue

- packages/frontend/package.json
- packages/frontend/src/components/Backdrop/Modal.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/PageLayout/pageLayout.module.css
- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
- packages/frontend/src/components/Sidebar/sidebar.module.css
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/SavedSearches/EditSearchesItem.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/storybook/package.json
- pnpm-lock.yaml
Bruker `selectedPartyIds` for å hente dialoger (søk og inbox). 
Fikser også et par småting:
- Valg av "Alle virksomheter" ble ikke reflektert i dropdown
- MenuHeader viste ikke riktig person bestandig ved valg.
> feat: use selected party ids when fetching dialogs

- packages/frontend/package.json
- packages/frontend/src/components/Backdrop/Modal.tsx
- packages/frontend/src/pages/SavedSearches/EditSearchesItem.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearches.tsx
- packages/storybook/package.json
- pnpm-lock.yaml
> chore: update to design-systemet@next

- packages/frontend/src/api/useDialogs.tsx
> fix: fixes flaky fetching assement for skeleton rendering

- packages/docs/blog/2021-08-26-welcome/index.md
- packages/docs/blog/authors.yml
> chore(docs): update authors for docs

- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
Adds Backdrop to PartyDropdown
Fixes https://github.com/digdir/dialogporten-frontend/issues/882
> fix: add dropdown on party dropdown in order to preventmultiple dropdowns open at once

- packages/frontend/src/app.css
- packages/frontend/src/components/Footer/footer.module.css
- packages/frontend/src/components/Header/AltinnLogo.tsx
- packages/frontend/src/components/Header/altinnLogo.module.css
- packages/frontend/src/components/Header/header.module.css
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/InboxItemsHeader.tsx
- packages/frontend/src/components/InboxItem/inboxItems.module.css
- packages/frontend/src/components/InboxItem/inboxItemsHeader.module.css
- packages/frontend/src/components/MenuBar/MenuItem.tsx
- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/PageLayout/pageLayout.module.css
- packages/frontend/src/components/Sidebar/Sidebar.tsx
- packages/frontend/src/components/Sidebar/sidebar.module.css
- packages/frontend/src/globals.css
> fix: div layout fixes

- packages/frontend/src/components/Footer/Footer.tsx
- packages/frontend/src/components/Footer/footer.module.css
- packages/frontend/src/components/MenuBar/MenuItem.tsx
- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/MenuBar/navigationMenuBar.module.css
> fix: fixes footer

- packages/frontend/src/components/PageLayout/pageLayout.module.css
- packages/frontend/src/pages/Inbox/inbox.module.css
- packages/frontend/src/pages/InboxItemPage/inboxItemPage.module.css
- packages/frontend/src/pages/InboxItemPage/inboxItemPageSkeleton.module.css
> fix: fixes alignment for inbox details and adds box shadow to inbox details

- packages/bff-types-generated/queries/parties.fragment.graphql
- packages/frontend/src/api/useParties.ts
- packages/frontend/src/components/PageLayout/PageLayout.tsx
> feat: use end user as default selected party

- packages/frontend/src/components/Footer/footer.module.css
> fix: replace padding with margin for misaligned horizontal line on smaller screens

- packages/bff/package.json
- pnpm-lock.yaml
No changes.
https://npmdiff.dev/%40digdir%2Fdialogporten-schema/1.11.0-161c42b/1.12.0
> chore: update dialogporten-schema to 1.12.0

- packages/frontend/src/components/Avatar/avatar.module.css
- packages/frontend/src/components/Badge/Badge.tsx
- packages/frontend/src/components/Badge/badge.module.css
- packages/frontend/src/components/Badge/index.ts
- packages/frontend/src/components/DropdownMenu/dropdownList.module.css
- packages/frontend/src/components/DropdownMenu/dropdownList.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/AddFilterButton.tsx
- packages/frontend/src/components/FilterBar/AddFilterButton/addFilterButton.module.css
- packages/frontend/src/components/FilterBar/FilterButton/FilterButton.tsx
- packages/frontend/src/components/FilterBar/FilterButton/filterButton.module.css
- packages/frontend/src/components/HorizontalLine/horizontalLine.module.css
- packages/frontend/src/components/MenuBar/MenuItem.tsx
- packages/frontend/src/components/MenuBar/NavigationDropdownSubMenuProfile.tsx
- packages/frontend/src/components/MenuBar/NavigationMenuBar.tsx
- packages/frontend/src/components/MenuBar/menuItem.module.css
- packages/frontend/src/components/MenuBar/navigationDropdownMenu.module.css
- packages/frontend/src/components/MenuBar/navigationMenuBar.module.css
- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
- packages/frontend/src/components/PartyDropdown/partyDropdown.module.css
- packages/frontend/src/components/index.ts
- packages/storybook/src/stories/Badge/badge.stories.tsx
Create a story for variants and sizes for documentation.
Replace all occurences of similar components with Badge.
Small adjustments for layout and weights in order to align with design with new changes.
> feat: new Badge component

- .github/workflows/ci-cd-prod.yml
> ci: add production workflow

- .azure/applications/bff-migration-job/prod.bicepparam
- .azure/applications/bff/prod.bicepparam
- .azure/applications/frontend/prod.bicepparam
- .azure/infrastructure/prod.bicepparam
Environment used throughout both Dialogporten and Arbeidsflate in Azure is "prod".
> fix(azure): rename environment parameter for production

- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/Avatar/Avatar.tsx
- packages/frontend/src/components/Avatar/avatar.module.css
- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- packages/frontend/src/components/InboxItem/inboxItem.module.css
- packages/frontend/src/components/InboxItem/inboxItemDetail.module.css
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/filters.spec.ts
- packages/frontend/src/pages/Inbox/filters.ts
- packages/storybook/src/stories/Avatar/avatar.stories.tsx
Support imageURL in Avatar.
Closes [#972](https://github.com/digdir/dialogporten-frontend/issues/972)
> feat: adds image url to avatar

- .github/workflows/ci-cd-prod.yml
- .github/workflows/dispatch-deploy-infrastructure.yml
Image is already built in the staging-step so we do not want to re-publish the docker image
> ci: ensure we do not build image again in production

- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/HorizontalLine/HorizontalLine.tsx
- packages/frontend/src/components/HorizontalLine/horizontalLine.module.css
- packages/frontend/src/components/Icons/PlusIcon/PlusIcon.tsx
- packages/frontend/src/components/Icons/PlusIcon/plusIcon.module.css
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/pages/SavedSearches/SavedSearchesActions/SavedSearchesActions.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem/SavedSearchesItem.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesItem/savedSearchesItem.module.css
- packages/frontend/src/pages/SavedSearches/SearchFilterTag/SearchFilterTag.tsx
- packages/frontend/src/pages/SavedSearches/SearchFilterTag/searchFilterTag.module.css
- packages/frontend/src/pages/SavedSearches/savedSearchesPage.module.css
> feat: Fixed Saved Search on mobile and updated according to new Figma design

- .azure/infrastructure/main.bicep
- .azure/modules/containerAppEnv/main.bicep
> feat(azure): add container app env for ephemeral environments

- packages/frontend/src/components/Header/search.module.css
> fix: incorrect icon size for close icon on mobile

- packages/frontend/src/components/GlobalMenuBar/NavigationDropdownSubMenuInbox.tsx
> fix: click saved searches button from global menu should also close global menu

- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/Header/search.module.css
> fix: Saved searches in dropdown menu on mobile

- .azure/infrastructure/prod.bicepparam
- .azure/infrastructure/staging.bicepparam
> fix(azure): use correct ssh public key env variable

- CODEOWNERS
> chore(github): add infra to codeowners

- CODEOWNERS
> chore: restructure codeowners to ensure correct review order

- .github/CODEOWNERS
- CODEOWNERS
> chore: refactor and put codeowners in .github

- packages/frontend/src/components/PageLayout/PageLayout.tsx
> fix: correct badge count for selected parties instead of all parties

- packages/storybook/src/stories/embeddable-markdown-html/markdown.stories.tsx
> fix: typo in type used for markdown story

- packages/bff-types-generated/queries/savedSearchesFields.fragment.graphql
- packages/bff/src/graphql/types/savedSearches.ts
- packages/frontend/src/components/GlobalMenuBar/NavigationDropdownSubMenuInbox.tsx
- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/PartyDropdown/PartyDropdown.tsx
- packages/frontend/src/components/PartyDropdown/PartyList.tsx
- packages/frontend/src/components/PartyDropdown/mergeParties.spec.ts
- packages/frontend/src/components/PartyDropdown/mergeParties.ts
- packages/frontend/src/components/Sidebar/Sidebar.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx
- packages/frontend/src/pages/SavedSearches/savedSearchesPage.module.css
- packages/frontend/src/pages/SavedSearches/useSavedSearches.ts
> feat: saved searches refined

- packages/embeddable-markdown-html/src/markdown.tsx
- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- packages/frontend/src/components/MainContentReference/MainContentReference.tsx
- packages/frontend/src/components/MainContentReference/index.ts
- packages/frontend/src/pages/InboxItemPage/inboxItemPage.module.css
> feat: fetch and display embeddable content

- .azure/applications/bff-migration-job/prod.bicepparam
- .azure/applications/bff-migration-job/staging.bicepparam
- .azure/applications/bff-migration-job/test.bicepparam
- .azure/applications/bff/prod.bicepparam
- .azure/applications/bff/staging.bicepparam
- .azure/applications/bff/test.bicepparam
> fix(bff): rename oidc host names

- .github/workflows/ci-cd-prod.yml
Had an issue with the dry-run of the deployment succeeded, but the actual deployment was never triggered. Since infrastructure deployment was skipped, deployment of apps would be skipped to.
> ci: run deployment of apps regardless of previous skipped jobs

- packages/bff-types-generated/queries/parties.fragment.graphql
- packages/frontend/src/api/useParties.ts
Så i prod at slettet aktør dukket opp i aktørlista (partydropdown).
Burde kanskje ikke vises i innboksen?
@alexdigdir @ingefossland
> fix: hide parties that are deleted

- packages/bff/package.json
- packages/bff/src/app.ts
- packages/bff/src/auth/oidc.ts
- packages/bff/src/azure/HealthProbes.ts
- packages/bff/src/data-source.ts
- packages/bff/src/run-migration.ts
- packages/bff/src/server.ts
- packages/bff/src/types.d.ts
- pnpm-lock.yaml
- turbo.json
Use the node logger in the `bff` service. Next steps is to publish this to `npm` for others to use
> feat(bff): use node logger

- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/featureFlags/FeatureFlags.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
Bulk actions now hidden behind Feature Flag:
> feat: Added Feature Flag for disabling bulk actions

- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/Header/search.module.css
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- packages/frontend/src/components/InboxItem/inboxItemDetail.module.css
- packages/frontend/src/components/MetaDataFields/metaDataFields.module.css
> feat: fixes meta fields UI for inbox details

- .azure/applications/bff-migration-job/main.bicep
- .azure/applications/bff/main.bicep
> feat(bff): use json as logger format

- packages/frontend/src/pages/Inbox/Inbox.tsx
> feat: Hide select button with feature flag

- packages/bff/src/app.ts
- packages/bff/src/auth/oidc.ts
- packages/bff/src/azure/HealthProbes.ts
- packages/bff/src/data-source.ts
- packages/bff/src/run-migration.ts
- packages/bff/src/server.ts
- packages/node-logger/README.md
- packages/node-logger/src/index.ts
Related to https://github.com/digdir/dialogporten/issues/1053
Fastify expects an instance of a pino-logger, so to make it easy for ourselves, we export the pino-logger directly. 
Result with default formatter (pretty):
> feat(bff): use node-logger in fastify

- .azure/applications/bff-migration-job/main.bicep
- .azure/applications/bff/main.bicep
- .azure/applications/frontend/main.bicep
- compose.yml
Even though we do not use this for anything specific, some packages that we use might be more performant or alter behaviour based on this environment variable. Using NODE_ENV=production in all environment to get the same behaviour in all environments
> fix: set node_env to production

- packages/frontend/src/components/Header/SearchDropdown.tsx
- packages/frontend/src/pages/Inbox/InboxSkeleton.tsx
> fix: Clicking a saved search in search dropdown

- .github/actions/install/action.yaml
Seems like this is needed in order for npm to be set up properly to publish npm packages
> ci: use registry url when setting up node

- packages/node-logger/.npmignore
- packages/node-logger/package.json
> chore(node-logger): fix publishing of npm package

- packages/bff/package.json
- packages/frontend/src/api/useDialogs.tsx
- pnpm-lock.yaml
> chore: update dialogporten-schema v.16.0-8214acbfq

- packages/bff/src/graphql/api.ts
> fix: adds token to context since session object is needed entirely

- packages/bff/src/auth/verifyToken.ts
> fix: remove console line

- packages/bff/src/instrumentation.ts
> chore(bff): ignore liveness and readiness probes for OT

- packages/bff/src/auth/oidc.ts
Fikser #1059 
~Foreløpig aksepterer ikke BE tok med dette scopet, så denne er ikke `safe to merge`.~
> fix: dialogporten.noconsent scope

- packages/bff/package.json
- pnpm-lock.yaml
> chore: use 1.18.0-4328427 of dialgporten-schema

- packages/frontend/src/api/useDialogByIdSubscription.ts
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- packages/frontend/src/components/InboxItem/inboxItemDetail.module.css
> fix: update event handlers

- packages/bff/package.json
- packages/bff/src/graphql/subscription.ts
- packages/frontend/src/api/useDialogByIdSubscription.ts
- pnpm-lock.yaml
Finalizes basics for write actions.
> feat: difference behaviour based on if dialog update event was a delete or update action

- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/components/InboxItem/inboxItem.module.css
Fixes https://github.com/digdir/dialogporten-frontend/issues/1152
> fix: font-weight for title in InboxItem, differing between read and unread

- packages/bff-types-generated/queries/dialog.fragment.graphql
- packages/bff/package.json
- packages/frontend/src/mocks/dialogs/helper.ts
- pnpm-lock.yaml
> fix: remove deprecated relatedActivityId

- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
> fix: dialog attachments should be opened in a new window or tab

- .azure/infrastructure/main.bicep
- .azure/modules/applicationInsights/availabilityTest.bicep
- .azure/modules/applicationInsights/create.bicep
> chore(bff): set up availability test for bff

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchString.tsx
- pnpm-lock.yaml
Showing search results in inbox from whatever route when a search on key press and on click. 
#1498
> fix: update to altinn-components v 0.8.3 for fixing on click on autocomplete to dismiss search bar

- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx
- packages/frontend/src/pages/SavedSearches/useSavedSearches.ts
Unable to save search because hooks were used outside of components
#1580
> fix: unable to save search

- packages/frontend/src/components/PageLayout/Search/useSearchString.tsx
- packages/frontend/tests/stories/loginPartyContext.spec.ts
> fix: read search query param on reload

- packages/frontend/package.json
- packages/frontend/src/components/MenuBar/MenuItem.tsx
- packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx
- pnpm-lock.yaml
Updates to latest version of altinn-components, fixes and implements a minor changes to autocomplete and menu items.
> fix: ui improvements to autocomplete dialog items and menu

- packages/bff/src/graphql/fastifyHeaders.ts
- packages/bff/src/graphql/subscription.ts
- packages/bff/src/server.ts
Etter å ha kjørt penetrasjonstest av Arbeidsflate har vi fått noen små-plukk som kan forbedres. 
Denne PRen legger til headers som foreslått i pentest rapporten.
- [#1491](https://github.com/digdir/dialogporten-frontend/issues/1491)
> chore: Added headers to BFF responses according to pentest feedback

- packages/bff/src/server.ts
- [#1490](https://github.com/digdir/dialogporten-frontend/issues/1490)
> fix: Set httpOnly to true when using https

- packages/bff/src/entities.ts
- packages/bff/src/graphql/functions/profile.ts
- packages/bff/src/graphql/functions/savedsearch.ts
- packages/bff/src/graphql/types/mutation.ts
- packages/bff/src/graphql/types/query.ts
- packages/frontend/src/components/FilterBar/dateInfo.spec.ts
- [#1638](https://github.com/digdir/dialogporten-frontend/issues/1638)
> chore: Refactor graphql functionality

- packages/frontend/src/api/useParties.ts
- packages/frontend/tests/stories/loginPartyContext.spec.ts
> fix: url query for changing party in useParties

- packages/frontend/src/components/PageLayout/Accounts/badge.spec.ts
- packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
> fix: include sub parties in accounts results in global menu

- .azure/modules/redis/main.bicep
- .azure/modules/virtualMachine/main.bicep
- .github/actions/azure-login/action.yml
- .github/workflows/workflow-deploy-apps.yml
- .github/workflows/workflow-deploy-infrastructure.yml
Ensure that bicep is upgraded
https://github.com/Altinn/dialogporten/pull/1593
> ci: fix infrastructure deployments

- .github/workflows/workflow-deploy-apps.yml
- .github/workflows/workflow-deploy-infrastructure.yml
> chore(azure): remove use of custom az cli version

- packages/bff/package.json
- pnpm-lock.yaml
- turbo.json
By using published npm package for node-logger instead of workspace dependency to rule out circular depedency.
> chore: trying to fix verify bff deploy

- packages/node-logger/package.json
> chore(node-logger): ensure package.json has correct repo url

- packages/bff/src/entities.ts
- packages/bff/src/migrations/1737375697452-add-migration-column.ts
The plan here is to test the CI/CD pipeline, then revert changes in entities file and nuke db again, and run initial db migrations again. This PR is just to make sure the db migrations works as expected, as a dry run before we have to do it "for real".
- [#1698](https://github.com/Altinn/dialogporten-frontend/issues/1698)
> chore: Test CI/CD database migrations

- packages/frontend/src/mocks/data/stories/search-flow/dialogs.ts
- packages/frontend/tests/index.ts
- packages/frontend/tests/stories/searchFlow.spec.ts
[#1578](https://github.com/Altinn/dialogporten-frontend/issues/1578)
> chore: Add playwright tests for search flow

- scripts/database-forwarder/README.md
- scripts/database-forwarder/forward.sh
> chore: database-forwarder

- .github/workflows/workflow-check-for-changes.yml
The check-for-changes related to migrations were not triggered, since the a file was deleted as the only change. Need to use modified to ensure we pick that up: https://github.com/Altinn/dialogporten-frontend/commit/e8ad8223446a758cc94f7688a2617c468a16b47a
- #N/A
> ci: ensure check for changes picks up when file has been removed

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/utils/useWindowSize.tsx
- pnpm-lock.yaml
> fix: Render sidebar navigation items in the global menu on tablet viewports (768px-1024px)

- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchDialogs.tsx
- packages/frontend/src/mocks/data/stories/subparty-merged-with-party/dialogs.ts
- packages/frontend/src/mocks/data/stories/subparty-merged-with-party/parties.ts
- packages/frontend/tests/stories/flatPartySubParty.spec.ts
[#1689](https://github.com/Altinn/dialogporten-frontend/issues/1689)
> fix: SubParties missing in filters

- .github/workflows/workflow-playwright-test.yml
- packages/bff/src/entities.ts
- [#1720](https://github.com/Altinn/dialogporten-frontend/issues/1720)
> fix: Saved searches database issue

- packages/docs/docs/development/database+migration.md
- [#1706](https://github.com/Altinn/dialogporten-frontend/issues/1706)
> chore: Tested migration with pre-existing data and updated docs

- compose.yml
- packages/bff/src/config.ts
- [#1737](https://github.com/Altinn/dialogporten-frontend/issues/1737)
> fix: Secure cookies in staging/test/prod

- compose.yml
- packages/bff/src/config.ts
This reverts commit 935e3a3e44da9f36633bd38494e663d9117da11e.
> fix: Revert "fix: Secure cookies in staging/test/prod"

- .azure/infrastructure/prod.bicepparam
Same as this but for production: https://github.com/Altinn/dialogporten-frontend/pull/1745
- #1684
> fix(infra): use correct ssl certificate in app gateway for production

- .azure/applications/bff/test.bicepparam
> fix(bff): disable secure cookie in test

- .azure/applications/bff/test.bicepparam
When environment variables are defined, we get a redirect loop. Need to investigate why the environment values, although false, is somehow not working, but when removing the environment variables it works 🤔
> fix(bff): ensure no redirect loop in test

- packages/bff/src/config.ts
- packages/bff/src/server.ts
> fix: process boolean variables correctly with zod

- packages/bff/src/config.ts
> fix: set default enable_graphiql to true

- packages/bff/package.json
- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx
- pnpm-lock.yaml
It also updates to latest version of altinn-components (and fixes some changes) and dialogporten-schema
- #1722
> fix: saved search input didnt get correct initial value

- .azure/applications/bff/test.bicepparam
> fix: cookie env var

- packages/bff/src/server.ts
> fix: Added sameSite true for cookies

- .azure/applications/bff/test.bicepparam
- packages/bff/src/server.ts
> fix: revert attempts to secure cookie

- .github/workflows/ci-cd-pull-request.yml
If changing infrastructure or other files that are not related to the applications, we don't want to run the `build-and-test` workflow.
- #N/A
> ci: avoid running build and test unless relevant files changed

- .azure/applications/bff/yt01.bicepparam
- .azure/infrastructure/yt01.bicepparam
> chore(infra): use correct hostname for yt01

- packages/bff/src/auth/oidc.ts
- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/mocks/handlers.ts
- packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx
- packages/frontend/tests/stories/common.ts
- packages/frontend/tests/stories/dialogDetails.spec.ts
- packages/frontend/tests/stories/filter.spec.ts
- packages/frontend/tests/stories/flatPartySubParty.spec.ts
- packages/frontend/tests/stories/inboxItemPage.spec.ts
- packages/frontend/tests/stories/loginPartyContext.spec.ts
- packages/frontend/tests/stories/messageNavigation.spec.ts
- packages/frontend/tests/stories/savedSearch.spec.ts
- packages/frontend/tests/stories/searchFlow.spec.ts
- packages/frontend/tests/stories/select-account.spec.ts
- packages/frontend/tests/stories/sidebar.spec.ts
- pnpm-lock.yaml
> chore: update playwright tests after bump of altinn-components

- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/mocks/data/stories/sender-name/dialogs.ts
- packages/frontend/tests/stories/senderName.spec.ts
- pnpm-lock.yaml
[#1760](https://github.com/Altinn/dialogporten-frontend/issues/1760)
> feat: Overwrite senderName if provided

- packages/bff/src/graphql/types/query.ts
[#1763](https://github.com/Altinn/dialogporten-frontend/issues/1763)
> feat: Sort saved searches

- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
> fix: icons missing in global menu

- packages/frontend/src/main.tsx
- packages/frontend/vite.config.ts
[#1726](https://github.com/Altinn/dialogporten-frontend/issues/1726)
> chore: Dislpay app version info in console

- packages/frontend/vite.config.ts
[#1726](https://github.com/Altinn/dialogporten-frontend/issues/1726)
> fix: Log info correct app version

- .azure/infrastructure/main.bicep
- .azure/modules/applicationGateway/main.bicep
Enables diagnostic settings for logs so we can view access logs in Azure and Grafana
- https://github.com/Altinn/dialogporten/issues/1693
> feat(infra): enable access logs for application gateway

- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/InboxItem/InboxItem.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.spec.ts
- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchString.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/mocks/data/stories/search-sender/dialogs.ts
- packages/frontend/src/mocks/handlers.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/tests/stories/searchSenders.spec.ts
[#1771](https://github.com/Altinn/dialogporten-frontend/issues/1771)
> feat: Add autocomplete senders suggestions

- .gitignore
- compose.yml
- data/homepage/config/services.yaml
- dynamic.yml
- homarr-config.json
- packages/bff/src/server.ts
- packages/docs/docs/development/graphql+IDE-support.md
- packages/docs/docs/development/https+certs.md
Using HTTPS locally ensures a realistic dev environment, prevents mixed-content issues, enables secure cookies, and aligns with production security settings—making debugging and testing more reliable.
Note: Both https and http should locally.
Set up HTTPS for `app.localhost`, `localhost`, and `docs.localhost` 
(from root of the project)
```sh
brew install mkcert nss
mkcert -install
mkcert -cert-file certs/cert.crt -key-file certs/key.pem app.localhost localhost docs.localhost
openssl x509 -in certs/cert.crt -out certs/cert.pem -outform PEM
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain certs/cert.pem
make compose-down
docker stop $(docker ps -a -q)
make dev
```
> chore: secure https with self-signed cert locally with Traefik

- packages/frontend/src/pages/Inbox/filters.ts
> fix: incorrect date for calculating date options - forgot to remove static date for testing

- packages/frontend/src/components/ProfileButton/ProfileButton.tsx
- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
Improvement / forgotten step in #1590 
- #1590
> fix: re-potion saved search button

- packages/frontend/src/api/useDialogByIdSubscription.ts
[#1803](https://github.com/Altinn/dialogporten-frontend/issues/1803)
> fix: Refetch data after gui action delete

- packages/frontend/src/components/AdditonalInfoContent/AdditonalInfoContent.tsx
- packages/frontend/src/components/InboxItem/inboxItemDetail.module.css
> fix: replace additional info content with DialogSection from altinn-components

- packages/docs/docs/deployment/infrastructure.md
> docs: add database-forwarder to readme

- packages/frontend/src/components/PageLayout/PageLayout.tsx
> fix: scroll to top on navigating between routes

- packages/frontend/package.json
- packages/frontend/src/api/useDialogById.tsx
- packages/frontend/src/components/InboxItem/InboxItemDetail.tsx
- packages/frontend/src/components/Transmission/Transmission.tsx
- pnpm-lock.yaml
> fix: show sender name if provided for transmission

- packages/frontend/src/components/ProfileButton/ProfileButton.tsx
- packages/frontend/src/components/ProfileButton/profileButton.module.css
- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
- packages/frontend/src/components/SavedSearchButton/savedSearchEnabled.spec.ts
- packages/frontend/src/components/SavedSearchButton/savedSearchEnabled.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/useFilters.tsx
Also fixes a couple of small cosmetic issues:
- No loading when parties are being fetched
- Small glitch on height of saved search button 
- #1870
> fix: saved search button was visible even though no filters were applied

- packages/frontend/package.json
- packages/frontend/src/pages/Inbox/Inbox.tsx
- pnpm-lock.yaml
[#1848](https://github.com/Altinn/dialogporten-frontend/issues/1848)
> fix: Add sorting function to DialogList

- packages/frontend/src/pages/Inbox/filters.ts
> fix: remove filters that should not be displayed

- packages/frontend/src/pages/Inbox/Inbox.tsx
[#1848](https://github.com/Altinn/dialogporten-frontend/issues/1848)
> fix: Adjust sorting function for DialogList

- packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx
> feat: Hide 'All actors' button if user has more than 20 parties available

- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
[#1882](https://github.com/Altinn/dialogporten-frontend/issues/1882)
> fix: Fix loading dialogs stuck after refresh

- packages/frontend/src/api/useDialogByIdSubscription.ts
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchDialogs.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1855
https://github.com/Altinn/dialogporten-frontend/issues/1909
> fix: Refetch data on going back from dialog, avoid unnecessary request when only org is provided

- packages/frontend/package.json
- pnpm-lock.yaml
Tar inn siste versjon av altinn-components for å løse #1912 og https://github.com/Altinn/altinn-components/issues/288
- #1912
> fix: issues with dialog actions with click away not working and primary button in combo button not being triggered

- packages/frontend/src/components/PageLayout/PageLayout.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1883
> fix: Remove search parameters if searh value is empty

- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/useGroupedDialogs.spec.tsx
- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
https://github.com/Altinn/dialogporten-frontend/issues/1878
> fix: Fix grouping dialogs by updatedAt, add sorting dialogs by updatedAt

- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
Value for inconclusive count varied for selected party, wrong value was used.
- #1660
> fix: The numbers in the 'actor menu' do not match either the new or the total number of dialogues

- packages/frontend/index.html
> feat: Added integrity check for Altinn CDN css file

- Readme.md
> docs: add info about docs and how to contribute

- packages/bff-types-generated/queries/parties.fragment.graphql
- packages/frontend/src/api/normalizeParties.spec.ts
- packages/frontend/src/api/useDialogs.tsx
- packages/frontend/src/api/useParties.ts
- packages/frontend/src/components/PageLayout/Accounts/badge.spec.ts
- packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx
- packages/frontend/src/mocks/data/base/parties.ts
- packages/frontend/src/mocks/data/stories/dialog-count/parties.ts
- packages/frontend/src/mocks/data/stories/english-1/parties.ts
- packages/frontend/src/mocks/data/stories/subparty-merged-with-party/parties.ts
> feat: Exclude Parent Parties When Only Access to Sub-Parties

- packages/frontend/src/api/useDialogs.tsx
> chore: Fix CI/CD pipeline TS error

- packages/frontend/package.json
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/1812
> fix: update ac to 21.6, fix filtering of gui actions

- .azure/infrastructure/main.bicep
- .azure/modules/vnet/main.bicep
Adding a separate subnet for the ssh-jumper in order to restrict networking access further
- https://github.com/Altinn/dialogporten/issues/1995
> fix(infra): separate subnet for ssh jumper with restricted rules

- scripts/database-forwarder/README.md
- scripts/database-forwarder/forward.sh
Preparing the script to add JIT configuration. This is a refactor that improves the feedback to the user and improves readability
- https://github.com/Altinn/dialogporten/issues/1995
> chore(database-forwarder): refactor

- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.tsx
> fix: prevent duplicate entries of searching for same sender

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/tests/stories/flatPartySubParty.spec.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/1617
> feat: Enable virtualization for accounts lists

- .azure/modules/virtualMachine/main.bicep
Will enable Azure to check for patch updates every 24 hours. 
- #N/A
> fix(infra): ensure we enable periodic assessment updates for ssh-jumpers

- packages/frontend/.gitignore
- packages/frontend/package.json
- packages/frontend/src/components/BetaBanner/BetaBanner.tsx
- packages/frontend/src/components/DialogToolbar/DialogToolbar.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/tests/accessibility/axe.test.ts
- packages/frontend/tests/index.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/1914
> chore: Add accessibility tests for every view and fix accessibility violations

- packages/frontend/package.json
- packages/frontend/src/api/utils/activities.tsx
- pnpm-lock.yaml
Change sort order from asc to desc on creation date for activites / transmissions in dialog history after changes from design.
- #1521
> fix: change sort order for items in dialog history for activities

- renovate.json
> chore(renovate): change to extend local>Altinn/renovate-config instead of DigDir

- packages/bff-types-generated/queries/AddFavoriteActor.graphql
- packages/bff-types-generated/queries/DeleteFavoriteActor.graphql
- packages/bff-types-generated/queries/profile.graphql
- packages/bff/src/entities.ts
- packages/bff/src/graphql/functions/profile.ts
- packages/bff/src/graphql/types/mutation.ts
- packages/bff/src/graphql/types/profile.ts
- packages/bff/src/graphql/types/query.ts
- packages/bff/src/migrations/1744295493806-add-favorite-actors.ts
- packages/frontend/src/api/queries.ts
- packages/frontend/src/profile/useProfile.tsx
Denne PRen implementerer en midlertidig løsning for henting og lagring av favorittaktører.
Det er ikke mulig å teste denne PRen (Kun backend implementasjon, dette kan testes i kommende oppgaver der det tas i bruk i frontend).
- #2035
> feat: Added interim solution for storing actor favorites in BFF

- .github/workflows/ci-cd-main.yml
- .github/workflows/ci-cd-prod-dry-run.yml
- .github/workflows/ci-cd-prod.yml
- .github/workflows/ci-cd-pull-request-release-please.yml
- .github/workflows/ci-cd-pull-request.yml
- .github/workflows/ci-cd-staging.yml
- .github/workflows/ci-cd-yt01.yml
- .github/workflows/dispatch-deploy-apps.yml
- .github/workflows/workflow-deploy-apps.yml
- .github/workflows/workflow-deploy-infrastructure.yml
- https://github.com/Altinn/dialogporten/issues/2186
> ci: Change GitHub action arm-deploy to bicep-deploy

- packages/bff/src/migrations/1744295493806-add-favorite-actors.ts
> chore: Trigger CI/CD pipeline

- packages/frontend/src/App.tsx
- packages/frontend/src/pages/Profile/Actors/ActorListItem.tsx
- packages/frontend/src/pages/Profile/Actors/Actors.tsx
- packages/frontend/src/pages/Profile/Actors/actors.module.css
- packages/frontend/src/pages/routes.ts
Dette er bare et meget røft første utkast til aktør-siden. Denne PRen tar for seg hovedsaklig implementasjon av interim favoritt-lagring i BFF samt et grovt oppsett for design.
- #1823
> feat: Profil: Parties side

- packages/frontend/tests/accessibility/axe.test.ts
- packages/frontend/tests/stories/dateInput2024.spec.ts
- packages/frontend/tests/stories/filter.spec.ts
- packages/frontend/tests/stories/flatPartySubParty.spec.ts
- packages/frontend/tests/stories/languagePicker.spec.ts
- packages/frontend/tests/stories/loginPartyContext.spec.ts
> chore: uncomment accessibility tests

- .azure/modules/ssh-jumper/main.bicep
> fix(infra): upgrade os version for virtual machines

- .azure/modules/ssh-jumper/main.bicep
Version 24 is not yet supported by automatic patching. Changing to a supported version: https://learn.microsoft.com/en-gb/azure/virtual-machines/automatic-vm-guest-patching#supported-os-images
- #2027
> fix(infra): ensure vm version is supported by auto vm patching

- packages/frontend/package.json
- packages/frontend/src/components/DialogDetails/DialogDetails.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- pnpm-lock.yaml
https://github.com/Altinn/altinn-components/issues/386
> fix: add isLoading to dialogList

- .azure/modules/containerAppEnv/main.bicep
Enable HA for Container App Environment for all environments. This requires recreation of the container app environment.
- https://github.com/Altinn/dialogporten/issues/2133
> feat(infra): enable HA for container app envs

- packages/bff-types-generated/queries/dialogs.graphql
- packages/bff/package.json
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2056
> chore: exclude apiOnly dialogs from searchDialogs query

- packages/bff/src/auth/oidc.ts
Changed scope in order for the user not to have to consent when logging in.
PS! Not to be merged until scope is updated in Samarbeidsportalen (we devs have lost access to this portal).
- [#2067](https://github.com/Altinn/dialogporten-frontend/issues/2067)
> chore: Changed scope for Core Token Exchange

- Readme.md
- packages/frontend/package.json
- packages/frontend/playwright.config.ts
- packages/frontend/tests/fixtures.ts
- packages/frontend/tests/stories/DialogDetailPage.spec.ts
- packages/frontend/tests/stories/activities.spec.ts
- packages/frontend/tests/stories/dateInput2024.spec.ts
- packages/frontend/tests/stories/dialogDetails.spec.ts
- packages/frontend/tests/stories/filter.spec.ts
- packages/frontend/tests/stories/flatPartySubParty.spec.ts
- packages/frontend/tests/stories/languagePicker.spec.ts
- packages/frontend/tests/stories/loginPartyContext.spec.ts
- packages/frontend/tests/stories/messageNavigation.spec.ts
- packages/frontend/tests/stories/savedSearch.spec.ts
- packages/frontend/tests/stories/searchFlow.spec.ts
- packages/frontend/tests/stories/searchSenders.spec.ts
- packages/frontend/tests/stories/select-account.spec.ts
- packages/frontend/tests/stories/senderName.spec.ts
- packages/frontend/tests/stories/sidebar.spec.ts
- packages/frontend/tests/stories/smoke.spec.ts
- packages/frontend/tests/stories/transmissions.spec.ts
https://github.com/Altinn/dialogporten-frontend/issues/2070
> chore: Configure mobile test runner, add readme, fix tests

- .github/workflows/ci-cd-prod.yml
- .github/workflows/workflow-check-for-changes.yml
- .github/workflows/workflow-get-latest-deployed-version-info-from-github.yml
- Change the output name to the correct ones in the `ci-cd-prod.yml`-workflow
- Add some debug logs to changed files to get more insight
- #N/A
> ci: ensure correct files are diffed for production

- packages/frontend/package.json
- pnpm-lock.yaml
Fix to prevent unneccessary reload of page on enter in search bar when item is rendered as link
> fix: bump ac to 0.24.4 containing fix

- compose.yml
- packages/bff/src/config.ts
- packages/bff/src/graphql/functions/profile.ts
Removed subscription key from profile fetches as it is no longer needed.
- #2104
> chore: Remove subscription key when fetching profile data from Core

- packages/frontend/package.json
- packages/frontend/src/pages/Profile/Profile.tsx
- packages/frontend/src/pages/Profile/profile.module.css
- packages/frontend/src/profile/formatSSN.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2078
> feat: profile landing page layout

- packages/frontend/package.json
- pnpm-lock.yaml
> fix: bump to latest version of a-c which includes fix for badge

- packages/frontend/src/api/hooks/useDialogByIdSubscription.ts
- https://github.com/Altinn/dialogporten-frontend/issues/2117
> fix: keep query params when navigated to inbox upon dialog delete

- packages/frontend/src/pages/Profile/Actors/ActorListItem.tsx
- packages/frontend/src/pages/Profile/Actors/Actors.tsx
- packages/frontend/src/pages/Profile/Actors/actors.module.css
- packages/frontend/src/profile/useProfile.tsx
> feat: Added profile data to Actor page.

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/1617
> fix: Make actor lists responsive

- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2131
> fix: Fix mobile actor list styles

- .github/workflows/workflow-check-for-changes.yml
Minor changes like this one: https://github.com/Altinn/dialogporten-frontend/pull/2146 shouldn't trigger a full run of infra and app deployments.
- #N/A
> ci: avoid unecessary infra and app runs on irrelevant changes

- .github/ISSUE_TEMPLATE/user_story.yml
Korrigert for user story uten understrek.
N/A
> chore: fix on issue template for user story

- .gitignore
Initialized a memory bank for Cursor IDE. Ignoring until we see the need to make public
- #N/A
> chore: add cursor IDE folder to gitignore

- packages/frontend/package.json
- packages/frontend/src/pages/DialogDetailsPage/DialogDetailsPage.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/1957
https://github.com/Altinn/dialogporten-frontend/issues/1950
> feat: Scroll to previous position on going back from dialog details

- packages/bff/src/auth/oidc.ts
Clear cookie (if present) to ensure termination of session after clearing. Last bit of the puzzle.
- #2050
> fix: clear cookie (if present) after destroying session for front channel logout

- packages/frontend/src/api/hooks/useDialogs.tsx
- packages/frontend/src/components/PageLayout/Search/useAutocomplete.tsx
- packages/frontend/src/components/PageLayout/Search/useSearchAutocompleteDialogs.spec.ts
- packages/frontend/src/globals.css
- packages/frontend/src/pages/Inbox/filters.ts
Fixes issue in #1990 and implements #1734 by matching in all translations of the org name for suggested sender.
- #1990 
- #1734
> fix: suggested order order + query will produce the same outcome

- packages/bff/src/auth/oidc.ts
- packages/bff/src/server.ts
Final fix to get single logout working
- #2050
> fix: destroy current session if found directly - terminated session immediately

- packages/bff/src/auth/oidc.ts
> fix: use idp sid instead of session id for destroying session correctly

- packages/embeddable-markdown-html/package.json
- packages/frontend/package.json
- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
- packages/frontend/src/pages/Profile/Actors/Actors.tsx
- packages/frontend/src/pages/Profile/Profile.tsx
- packages/frontend/src/pages/SavedSearches/useSavedSearches.tsx
- packages/frontend/tests/stories/common.ts
- packages/frontend/tests/stories/dateInput2024.spec.ts
- packages/frontend/tests/stories/filter.spec.ts
- pnpm-lock.yaml
Updated altinn-components to v0.28.2
Removed dashboard cards as the design has changed. 
Fixed imports for ListItemBase
Fixed type import for QueryItemProps
https://github.com/Altinn/dialogporten-frontend/issues/2173
> fix: Fix breaking changes after ac v28 update

- .azure/modules/containerApp/main.bicep
- .azure/modules/containerAppJob/main.bicep
Used the wrong property for workload profile for the container apps and container app jobs.
- #N/A
> fix(infra): use correct param for workload profile for apps

- packages/frontend/src/useGlobalState.ts
https://github.com/Altinn/dialogporten-frontend/issues/2188
> fix: Fix tanstack query console errors

- .azure/modules/postgreSql/create.bicep
> fix(infra): add missing type for sku in postgresql

- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
- packages/frontend/tests/stories/languagePicker.spec.ts
- packages/frontend/tests/stories/senderName.spec.ts
https://github.com/Altinn/dialogporten-frontend/issues/2202
> fix: translation of sender to recipient word

- packages/frontend/src/pages/Profile/Activities/Activities.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2081
> feat: Add dummy profile activity page

- packages/frontend/src/pages/Inbox/Inbox.tsx
- https://github.com/Altinn/dialogporten-frontend/issues/2218
> fix: missing saved search for other folders than inbox

- packages/frontend/src/components/PageLayout/Footer/useFooter.tsx
> fix: remove Altinn As from footer

- packages/frontend/src/api/utils/normalizeFlattenParties.ts
- packages/frontend/src/api/utils/normalizeParties.spec.ts
- packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx
- https://github.com/Altinn/dialogporten-frontend/issues/1847
> fix: exclude parent parties when user only has access to sub parties from party list

- packages/frontend/src/pages/Inbox/filters.ts
- packages/frontend/src/pages/Inbox/useFilters.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2269
Spec: https://github.com/Altinn/dialogporten-frontend/issues/2269#issuecomment-3012932676
> fix: Include senders from search params in filters

- packages/frontend/src/App.tsx
- packages/frontend/src/components/ErrorBoundary/ErrorBoundary.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/constants/queryKeys.ts
- packages/frontend/src/pages/Error/Error.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/routes.ts
- packages/frontend/tests/stories/errorHandling.spec.ts
https://github.com/Altinn/dialogporten-frontend/issues/2187
> feat: add error page and error boundary logic

- packages/frontend/src/components/ErrorBoundary/ErrorBoundary.tsx
> fix: disable errorBoundary in dev

- packages/bff/src/graphql/types/organization.ts
Use emblem (SVG) if it exists in altinn-CDN instead of regular logo
- #2258
> feat(orgs): prioritize emblem over logo for org avatar with generic logo as fallback

- packages/frontend/package.json
- packages/frontend/src/api/hooks/useDialogs.tsx
- packages/frontend/src/api/utils/dialog.ts
- packages/frontend/src/components/SeenByModal/SeenByModal.tsx
- packages/frontend/src/mocks/data/base/dialogs.ts
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/useGroupedDialogs.spec.tsx
- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
- pnpm-lock.yaml
> feat: add seen by log details in modal from dialog list view

- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/Error/Error.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2308
> feat: Update error page content

- packages/frontend/package.json
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2328
> fix: Org logo looks off on dialog list item

- packages/frontend/package.json
- packages/frontend/src/components/BetaBanner/BetaBanner.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- pnpm-lock.yaml
- Banner now without close/hide button.
- Updated text using translations.
- Component updated in Altinn Components
- #1743
> feat: Banner now without close/hide button and updated text.

- packages/frontend/src/mocks/data/base/helper.ts
- packages/frontend/src/pages/Inbox/filters.ts
- packages/frontend/tests/stories/dateInput2024.spec.ts
This PR includes skipped PW tests related to changes in filters. 
https://github.com/Altinn/dialogporten-frontend/issues/2345 should be resolved after changes are verified by QA @LeifHelstad 
https://github.com/Altinn/dialogporten-frontend/issues/2259
> fix: Filters now showing count label of all dialogs found

- packages/bff-types-generated/queries/parties.fragment.graphql
- packages/frontend/src/api/utils/normalizeParties.spec.ts
- packages/frontend/src/components/PageLayout/Accounts/badge.spec.ts
- packages/frontend/src/mocks/data/base/parties.ts
- packages/frontend/src/mocks/data/stories/dialog-count/parties.ts
- packages/frontend/src/mocks/data/stories/english-1/parties.ts
- packages/frontend/src/mocks/data/stories/subparty-merged-with-party/parties.ts
> feat: Added partyUuid to parties

- packages/frontend/package.json
- packages/frontend/tests/stories/profile/notifications.spec.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2340
> fix: Fix logo on dialog detailed view

- packages/bff-types-generated/queries/DeleteFavoriteActor.graphql
- packages/bff-types-generated/queries/profile.graphql
- packages/bff/src/graphql/functions/profile.ts
- packages/bff/src/graphql/types/mutation.ts
- packages/bff/src/graphql/types/profile.ts
- packages/bff/src/graphql/types/query.ts
- packages/frontend/src/api/queries.ts
- packages/frontend/src/pages/Profile/PartiesOverviewPage/DetailsComponents.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/partyFieldToAccountList.tsx
- packages/frontend/src/profile/useProfile.tsx
We have previously implemented our own "interim" solutions for saving favorites in groups, while waiting for Core to come up with the actual API.
Now, part of the API is ready, but it only supports one group (favorites) and not adding and handling other groups. 
This functionality is what has been implemented in this PR, replacing our own interim-solution.
Demo:
- #2349
> feat: Implement read/add/remove favorites from Core

- packages/frontend/src/components/BetaBanner/BetaBanner.tsx
> fix: Banner no longer covers filters on mobile

- packages/bff/src/graphql/types/organization.ts
- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
Forgot to prioritize emblem over logo in https://github.com/Altinn/dialogporten-frontend/pull/2315
- #2258
> fix: prioritize emblem over logo for org avatar with generic logo as fallback

- packages/frontend/package.json
- pnpm-lock.yaml
> fix: couple of missing aria attributes in search bar by upgrading to latest version of altinn-components

- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
-[#2394](https://github.com/Altinn/dialogporten-frontend/issues/2394)
> fix: Transmission sent/received count now showing correct numbers

- packages/frontend/package.json
- pnpm-lock.yaml
- https://github.com/Altinn/altinn-components/issues/560
> fix: bump a-c to latest to include logical keyboard navigation order in global layout

- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.spec.ts
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
> fix: maintain sidebar selection when viewing dialogs

- packages/frontend/package.json
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2424
> fix: bump up AC-lib for virtualized list fix

- packages/frontend/src/api/hooks/useDialogs.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Inbox/useGroupedDialogs.tsx
- packages/frontend/src/pages/Inbox/useMockError.tsx
> fix: show loading indicator for fetching when prev data is kept

- packages/bff/src/auth/oidc.ts
- packages/frontend/src/auth/url.ts
- packages/frontend/src/components/Login/AuthContext.tsx
See comment in #2450 - this does not change anything, only tidys up unneccessary code
> fix: simplify by always directing user to main entry on successful login

- packages/e2e/tests/inbox-smoke.spec.ts
> chore: fix e2e tests, use first link if many occure.

- packages/e2e/tests/inbox-smoke.spec.ts
- packages/frontend/package.json
- pnpm-lock.yaml
> feat: Update AC-lib with new awaiting labels

- packages/frontend/src/pages/Inbox/filters.ts
https://github.com/Altinn/dialogporten-frontend/issues/2268#issuecomment-3191352700
> fix: Hide sender filters with zero hits

- packages/frontend/package.json
- packages/frontend/tests/stories/searchFlow.spec.ts
- packages/frontend/tests/stories/sentAndAwaitingDialogs.spec.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2424#issuecomment-3190948675
> fix: Bump AC to v.0.37.0, remove double scrollbar

- packages/frontend/src/api/utils/transmissions.ts
> fix: ensure end-user transmissions are never marked as unread

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
- packages/frontend/tests/stories/languagePicker.spec.ts
- pnpm-lock.yaml
Update to latest version of altinn components for keyboard nav for context menu and locale switcher + introduce skip links.
> fix: improvements to accessbility: keyboard navigation + skiplink

- packages/e2e/playwright.config.ts
- packages/e2e/tests/inbox-smoke.spec.ts
> fix: Change e2e test actor, fix tests

- packages/frontend/src/auth/url.ts
- packages/frontend/src/components/PageLayout/PageLayout.tsx
> feat: change logo url in header

- .azure/applications/bff/main.bicep
- .azure/applications/bff/prod.bicepparam
- compose.yml
- package.json
- packages/bff/src/config.ts
- packages/bff/src/graphql/functions/profile.ts
- packages/bff/src/graphql/types/query.ts
- packages/frontend/src/App.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/featureFlags/FeatureFlags.ts
> feat: Hiding Profile pages in production

- .github/workflows/ci-cd-release-please.yml
Release please suddenly stopped working. Background: https://digdir.slack.com/archives/C079D6PAGDS/p1755860434350869?thread_ts=1755595462.906849&cid=C079D6PAGDS
Updating to new version which contains the fix.
- #N/A
> fix(release-please): update new version of release please

- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/About/About.tsx
> fix: prepare global menu for beta release + couple of fixes to about routing

- packages/frontend/package.json
- packages/frontend/src/app.spec.tsx
- packages/frontend/src/auth/url.ts
- packages/frontend/src/components/BetaModal/BetaModal.tsx
- packages/frontend/src/components/BetaModal/index.tsx
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/constants/queryKeys.ts
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/About/About.tsx
- pnpm-lock.yaml
- https://github.com/Altinn/dialogporten-frontend/issues/2547
> feat: introduce beta modal

- packages/frontend/src/components/PageLayout/PageLayout.tsx
> fix: floating button was incorrectly placed

- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- pnpm-lock.yaml
Adapt to deal with API changes from altinn-components and minor design tweaks
> fix: menu items for global menu

- packages/e2e/test-results/.last-run.json
> chore: remove test-results

- packages/frontend/src/App.tsx
> feat: Hiding profile pages in prod env

- packages/e2e/tests/saved-searches.spec.ts
> feat: Add e2e for saved searches

- packages/frontend/index.html
- packages/frontend/package.json
- pnpm-lock.yaml
> fix: change html title

- packages/bff-types-generated/queries/notificationAddressByOrgNumber.graphql
- packages/bff/src/graphql/functions/profile.ts
- packages/bff/src/graphql/types/query.ts
- packages/frontend/src/api/queries.ts
- packages/frontend/src/pages/Profile/NotificationsPage/NotificationsPage.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/NotificationSettings.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/partyFieldToAccountList.tsx
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
- [#2551](https://github.com/Altinn/dialogporten-frontend/issues/2551)
> feat: Implement Organization endpoint from core + bugfixes and more

- .azure/applications/bff/test.bicepparam
> chore: Disable Profile in Test env

- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/About/About.tsx
> fix: add links to about the new Altinn

- packages/frontend/src/analytics.ts
https://github.com/Altinn/dialogporten-frontend/issues/2625
> chore(analytics): filter out browser extension and cross-origin errors from Application Insights

- biome.jsonc
- package.json
- packages/bff-types-generated/package.json
- packages/frontend/package.json
- packages/frontend/public/mockServiceWorker.js
- packages/frontend/src/api/queries.ts
- pnpm-lock.yaml
> chore(deps): upgrade graphql request to use native fetch for improved header control

- package.json
- packages/docs/docs/notes/Presentational logic/embadable-content.mdx
- packages/embeddable-markdown-html/package.json
- packages/embeddable-markdown-html/src/markdown.tsx
- packages/embeddable-markdown-html/src/tags.ts
- packages/embeddable-markdown-html/tests/html.spec.tsx
- packages/embeddable-markdown-html/tests/markdown.spec.tsx
- packages/frontend/src/mocks/handlers.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2665
> feat: support for github flavored markdown for table support

- package.json
- packages/bff/src/graphql/subscription.ts
- packages/frontend/src/api/hooks/useDialogByIdSubscription.ts
- packages/frontend/src/components/DialogDetails/DialogDetails.tsx
- packages/frontend/src/pages/DialogDetailsPage/DialogDetailsPage.tsx
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2457
https://github.com/Altinn/dialogporten-frontend/issues/2673
> fix: wait on subscription to be established before loading fce

- package.json
- packages/frontend/package.json
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/pages/Inbox/filters.ts
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2681
> fix: duplicate test ids for sub items in sidemenu

- biome.jsonc
> chore(formatting): ignore ./package.json

- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/About/About.tsx
- packages/frontend/src/pages/DialogDetailsPage/DialogDetailsPage.tsx
- packages/frontend/src/pages/Error/Error.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Profile/Access/Access.tsx
- packages/frontend/src/pages/Profile/Activities/Activities.tsx
- packages/frontend/src/pages/Profile/Authorize/Authorize.tsx
- packages/frontend/src/pages/Profile/NotificationsPage/NotificationsPage.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/PartiesOverviewPage.tsx
- packages/frontend/src/pages/Profile/Profile.tsx
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx
- packages/frontend/src/utils/usePageTitle.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2583
> feat: Dymanic page title

- packages/frontend/src/hooks/usePageTitle.tsx
- packages/frontend/src/pages/About/About.tsx
- packages/frontend/src/pages/DialogDetailsPage/DialogDetailsPage.tsx
- packages/frontend/src/pages/Error/Error.tsx
- packages/frontend/src/pages/Inbox/Inbox.tsx
- packages/frontend/src/pages/Profile/Access/Access.tsx
- packages/frontend/src/pages/Profile/Activities/Activities.tsx
- packages/frontend/src/pages/Profile/Authorize/Authorize.tsx
- packages/frontend/src/pages/Profile/NotificationsPage/NotificationsPage.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/PartiesOverviewPage.tsx
- packages/frontend/src/pages/Profile/Profile.tsx
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
- packages/frontend/src/pages/SavedSearches/SavedSearchesPage.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2729
> fix: correct page title translations

- packages/frontend/src/components/BetaModal/BetaModal.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2566
> feat: Close button for welcome modal

- packages/frontend/src/pages/Profile/name.spec.ts
- packages/frontend/src/pages/Profile/name.ts
https://github.com/Altinn/dialogporten-frontend/issues/2735
> fix: Capitalize double names with dash

- packages/frontend/src/analytics.ts
- packages/frontend/src/hooks/usePageTracking.ts
- packages/frontend/src/pages/Profile/PartiesOverviewPage/CompanyNotificationSettings.tsx
* try/catch the trackPageView function
* Add mock functions for all exported functions when application insights is not enabled. 
* Ensure only pages that we have defined are tracked
- #N/A
> fix(frontend): make page tracking more robust

- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
> fix: remove unwanted logged in label in sidebar

- packages/frontend/package.json
- packages/frontend/src/onboardingTour/OnboardingPopover.tsx
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2566#issuecomment-3323773853
> fix: Focus trap beta modal and tour popover

- packages/frontend/src/analytics.ts
Adding cloudrolename and cloudroleinstance to easier identify the logs and metrics from the frontend
- #2323
> fix(frontend): make sure we can identify the app in AI easier

- packages/e2e/tests/inbox-smoke.spec.ts
- packages/e2e/tests/saved-searches.spec.ts
> fix: broken e2e tests after aria label change on close button

- packages/frontend/src/pages/Profile/PartiesOverviewPage/UserNotificationSettingsModal.tsx
> fix: User address change URL for test env

- packages/frontend/src/pages/Profile/PartiesOverviewPage/CompanyNotificationSettings.tsx
Validation for phone number updated to be the same as Altinn Core uses in their backend.
- #2711
> feat: Added phone number validation same as Core backend

- packages/frontend/src/components/PageLayout/Accounts/useAccounts.tsx
- packages/frontend/src/components/PageLayout/GlobalMenu/inboxMenu.tsx
- packages/frontend/src/components/PageLayout/GlobalMenu/profileMenu.tsx
- packages/frontend/src/components/PageLayout/GlobalMenu/shared.spec.ts
- packages/frontend/src/components/PageLayout/GlobalMenu/shared.tsx
- packages/frontend/src/components/PageLayout/GlobalMenu/useGlobalMenu.tsx
- packages/frontend/src/components/PageLayout/PageLayout.tsx
- packages/frontend/src/featureFlags/FeatureFlags.ts
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/Profile/Profile.tsx
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2811
https://github.com/Altinn/dialogporten-frontend/issues/2803
> feat: refactor global menu for profile + at23-test flow

- packages/frontend/src/pages/Profile/PartiesOverviewPage/CompanyDetails.tsx
Removes link indication for Organization number:
- #2801
> fix: Remove link indication for org no.

- packages/embeddable-markdown-html/src/html.tsx
- packages/embeddable-markdown-html/src/markdown.tsx
- packages/frontend/src/components/DialogDetails/DialogDetails.tsx
- packages/frontend/src/components/MainContentReference/MainContentReference.tsx
- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
https://github.com/Altinn/dialogporten-frontend/issues/2124
> chore: MainContentReference embeded content error handling

- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2759#issuecomment-3372138257
> fix: Fix savedSearch icon on Safari zoom

- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
https://github.com/Altinn/dialogporten-frontend/issues/2759#issuecomment-3372138257
> fix: saved search safari fix

- packages/frontend/src/i18n/resources/en.json
- packages/frontend/src/i18n/resources/nb.json
- packages/frontend/src/i18n/resources/nn.json
- packages/frontend/src/pages/Profile/NotificationsPage/CompanyNotificationSettingsModal.tsx
- packages/frontend/src/pages/Profile/NotificationsPage/NotificationsPage.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/AccountToolbar.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/CompanyDetails.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/CompanyNotificationSettings.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/PartiesOverviewPage.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/UserDetails.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/UserNotificationSettingsModal.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/partyFieldToAccountList.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/partyFieldToNotificationsList.tsx
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
- packages/frontend/src/pages/Profile/usePartiesWithNotificationSettings.tsx
- packages/frontend/src/pages/Profile/useProfile.tsx
- Implemented new design for notification settings (private and for virksomheter)
- Fixed links to inbox, now with context
- Grouping of actors on actor and notification page
- Persons (not yourself) will now show in lists
- Fixed bug were some parties were not showing
- Rewritten code to use new component in Altinn Components
- Fixed some race condition bugs
- #2869
- #2868
- [#2864](https://github.com/Altinn/dialogporten-frontend/issues/2864)
> feat: Fixed actor list bugs. Added grouping logic. Refactoring

- packages/frontend/package.json
- packages/frontend/src/components/SavedSearchButton/SaveSearchButton.tsx
- packages/frontend/src/pages/Profile/NotificationsPage/NotificationsPage.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/CompanyDetails.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/PartyDetailsSetting.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/UserDetails.tsx
- packages/frontend/src/pages/Profile/PartiesOverviewPage/partyFieldToNotificationsList.tsx
- packages/frontend/src/pages/Profile/Profile.tsx
- packages/frontend/src/pages/Profile/Settings/Settings.tsx
- pnpm-lock.yaml
https://github.com/Altinn/dialogporten-frontend/issues/2759
> fix: Fix savedsearch icon size and globalmenu icons on safari
